//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 10:48:26 AM CDT 
//


package com.officedepot;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BatteryInformationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BatteryInformationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="isBatteryRequired" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="isBatteryIncluded" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="batterySets" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="batterySet" type="{http://eai.officedepot.com/model/ODCommon}BatterySetType" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BatteryInformationType", namespace = "http://eai.officedepot.com/model/Inventory", propOrder = {
    "isBatteryRequired",
    "isBatteryIncluded",
    "batterySets"
})
public class BatteryInformationType {

    protected Boolean isBatteryRequired;
    protected String isBatteryIncluded;
    protected BatteryInformationType.BatterySets batterySets;

    /**
     * Gets the value of the isBatteryRequired property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsBatteryRequired() {
        return isBatteryRequired;
    }

    /**
     * Sets the value of the isBatteryRequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsBatteryRequired(Boolean value) {
        this.isBatteryRequired = value;
    }

    /**
     * Gets the value of the isBatteryIncluded property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsBatteryIncluded() {
        return isBatteryIncluded;
    }

    /**
     * Sets the value of the isBatteryIncluded property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsBatteryIncluded(String value) {
        this.isBatteryIncluded = value;
    }

    /**
     * Gets the value of the batterySets property.
     * 
     * @return
     *     possible object is
     *     {@link BatteryInformationType.BatterySets }
     *     
     */
    public BatteryInformationType.BatterySets getBatterySets() {
        return batterySets;
    }

    /**
     * Sets the value of the batterySets property.
     * 
     * @param value
     *     allowed object is
     *     {@link BatteryInformationType.BatterySets }
     *     
     */
    public void setBatterySets(BatteryInformationType.BatterySets value) {
        this.batterySets = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="batterySet" type="{http://eai.officedepot.com/model/ODCommon}BatterySetType" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "batterySet"
    })
    public static class BatterySets {

        @XmlElement(namespace = "http://eai.officedepot.com/model/Inventory", required = true)
        protected List<BatterySetType> batterySet;

        /**
         * Gets the value of the batterySet property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the batterySet property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBatterySet().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BatterySetType }
         * 
         * 
         */
        public List<BatterySetType> getBatterySet() {
            if (batterySet == null) {
                batterySet = new ArrayList<BatterySetType>();
            }
            return this.batterySet;
        }

    }

}
