//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 10:48:26 AM CDT 
//


package com.officedepot;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * information about the company
 * 
 * <p>Java class for CompanyIdentityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CompanyIdentityType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="businessName" type="{http://eai.officedepot.com/model/ODCommon}CompanyNameSimpleType" minOccurs="0"/&gt;
 *         &lt;element name="companyLegalName" type="{http://eai.officedepot.com/model/ODCommon}CompanyLegalNameSimpleType" minOccurs="0"/&gt;
 *         &lt;element name="inBusinessSinceYear" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="businessAddress" type="{http://eai.officedepot.com/model/ODCommon}AddressType" minOccurs="0"/&gt;
 *         &lt;element name="billingAddress" type="{http://eai.officedepot.com/model/ODCommon}AddressType" minOccurs="0"/&gt;
 *         &lt;element name="telephone" type="{http://eai.officedepot.com/model/ODCommon}PhonesType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="fax" type="{http://eai.officedepot.com/model/ODCommon}PhonesType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="email" type="{http://eai.officedepot.com/model/ODCommon}EmailAssociationType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CompanyIdentityType", propOrder = {
    "businessName",
    "companyLegalName",
    "inBusinessSinceYear",
    "businessAddress",
    "billingAddress",
    "telephone",
    "fax",
    "email"
})
@XmlSeeAlso({
    ManufacturerType.class
})
public class CompanyIdentityType {

    protected String businessName;
    protected String companyLegalName;
    protected BigInteger inBusinessSinceYear;
    protected AddressType businessAddress;
    protected AddressType billingAddress;
    protected List<PhonesType> telephone;
    protected List<PhonesType> fax;
    protected List<EmailAssociationType> email;

    /**
     * Gets the value of the businessName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusinessName() {
        return businessName;
    }

    /**
     * Sets the value of the businessName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusinessName(String value) {
        this.businessName = value;
    }

    /**
     * Gets the value of the companyLegalName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyLegalName() {
        return companyLegalName;
    }

    /**
     * Sets the value of the companyLegalName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyLegalName(String value) {
        this.companyLegalName = value;
    }

    /**
     * Gets the value of the inBusinessSinceYear property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getInBusinessSinceYear() {
        return inBusinessSinceYear;
    }

    /**
     * Sets the value of the inBusinessSinceYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setInBusinessSinceYear(BigInteger value) {
        this.inBusinessSinceYear = value;
    }

    /**
     * Gets the value of the businessAddress property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType }
     *     
     */
    public AddressType getBusinessAddress() {
        return businessAddress;
    }

    /**
     * Sets the value of the businessAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *     
     */
    public void setBusinessAddress(AddressType value) {
        this.businessAddress = value;
    }

    /**
     * Gets the value of the billingAddress property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType }
     *     
     */
    public AddressType getBillingAddress() {
        return billingAddress;
    }

    /**
     * Sets the value of the billingAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *     
     */
    public void setBillingAddress(AddressType value) {
        this.billingAddress = value;
    }

    /**
     * Gets the value of the telephone property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the telephone property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTelephone().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PhonesType }
     * 
     * 
     */
    public List<PhonesType> getTelephone() {
        if (telephone == null) {
            telephone = new ArrayList<PhonesType>();
        }
        return this.telephone;
    }

    /**
     * Gets the value of the fax property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fax property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFax().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PhonesType }
     * 
     * 
     */
    public List<PhonesType> getFax() {
        if (fax == null) {
            fax = new ArrayList<PhonesType>();
        }
        return this.fax;
    }

    /**
     * Gets the value of the email property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the email property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEmail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EmailAssociationType }
     * 
     * 
     */
    public List<EmailAssociationType> getEmail() {
        if (email == null) {
            email = new ArrayList<EmailAssociationType>();
        }
        return this.email;
    }

}
