//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 10:48:26 AM CDT 
//


package com.officedepot;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The consumer is the most recent "caller" of the ESB
 * 				service. This information must be populated by the application that
 * 				calls the ESB.
 * 
 * <p>Java class for ConsumerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConsumerType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="consumerName" type="{http://www.officedepot.com/model/transaction}ConsumerNameType"/&gt;
 *         &lt;element name="consumerTransactionID" type="{http://www.officedepot.com/model/transaction}ConsumerTrackingIDType" minOccurs="0"/&gt;
 *         &lt;element name="consumerMachineAddress" type="{http://www.officedepot.com/model/transaction}MachineAddressType" minOccurs="0"/&gt;
 *         &lt;element name="altTrackingIDs" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence maxOccurs="3"&gt;
 *                   &lt;element name="dataKeys" type="{http://www.officedepot.com/model/transaction}KeyAndValueType"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="clientRelease" type="{http://www.officedepot.com/model/transaction}ClientReleaseType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConsumerType", namespace = "http://www.officedepot.com/model/transaction", propOrder = {
    "consumerName",
    "consumerTransactionID",
    "consumerMachineAddress",
    "altTrackingIDs",
    "clientRelease"
})
public class ConsumerType {

    @XmlElement(required = true)
    protected String consumerName;
    protected String consumerTransactionID;
    protected String consumerMachineAddress;
    protected ConsumerType.AltTrackingIDs altTrackingIDs;
    protected String clientRelease;

    /**
     * Gets the value of the consumerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsumerName() {
        return consumerName;
    }

    /**
     * Sets the value of the consumerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsumerName(String value) {
        this.consumerName = value;
    }

    /**
     * Gets the value of the consumerTransactionID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsumerTransactionID() {
        return consumerTransactionID;
    }

    /**
     * Sets the value of the consumerTransactionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsumerTransactionID(String value) {
        this.consumerTransactionID = value;
    }

    /**
     * Gets the value of the consumerMachineAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsumerMachineAddress() {
        return consumerMachineAddress;
    }

    /**
     * Sets the value of the consumerMachineAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsumerMachineAddress(String value) {
        this.consumerMachineAddress = value;
    }

    /**
     * Gets the value of the altTrackingIDs property.
     * 
     * @return
     *     possible object is
     *     {@link ConsumerType.AltTrackingIDs }
     *     
     */
    public ConsumerType.AltTrackingIDs getAltTrackingIDs() {
        return altTrackingIDs;
    }

    /**
     * Sets the value of the altTrackingIDs property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConsumerType.AltTrackingIDs }
     *     
     */
    public void setAltTrackingIDs(ConsumerType.AltTrackingIDs value) {
        this.altTrackingIDs = value;
    }

    /**
     * Gets the value of the clientRelease property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientRelease() {
        return clientRelease;
    }

    /**
     * Sets the value of the clientRelease property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientRelease(String value) {
        this.clientRelease = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence maxOccurs="3"&gt;
     *         &lt;element name="dataKeys" type="{http://www.officedepot.com/model/transaction}KeyAndValueType"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dataKeys"
    })
    public static class AltTrackingIDs {

        @XmlElement(namespace = "http://www.officedepot.com/model/transaction", required = true)
        protected List<KeyAndValueType> dataKeys;

        /**
         * Gets the value of the dataKeys property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the dataKeys property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDataKeys().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link KeyAndValueType }
         * 
         * 
         */
        public List<KeyAndValueType> getDataKeys() {
            if (dataKeys == null) {
                dataKeys = new ArrayList<KeyAndValueType>();
            }
            return this.dataKeys;
        }

    }

}
