//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 10:48:26 AM CDT 
//


package com.officedepot;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CostInformationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CostInformationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="purchaseOrderCost" type="{http://eai.officedepot.com/model/Supplier}PurchaseOrderCostType" minOccurs="0"/&gt;
 *         &lt;element name="freightOnBoardCost" type="{http://eai.officedepot.com/model/ODCommon}FinanicalAmountType" minOccurs="0"/&gt;
 *         &lt;element name="averageFreightCost" type="{http://eai.officedepot.com/model/ODCommon}FinanicalAmountType" minOccurs="0"/&gt;
 *         &lt;element name="estimatedLandedCost" type="{http://eai.officedepot.com/model/ODCommon}FinanicalAmountType" minOccurs="0"/&gt;
 *         &lt;element name="priceProtectionEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="effectiveDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="systemClassifier" type="{http://eai.officedepot.com/model/ODCommon}SystemClassifierType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CostInformationType", namespace = "http://eai.officedepot.com/model/Supplier", propOrder = {
    "purchaseOrderCost",
    "freightOnBoardCost",
    "averageFreightCost",
    "estimatedLandedCost",
    "priceProtectionEnabled",
    "effectiveDate",
    "systemClassifier"
})
public class CostInformationType {

    protected PurchaseOrderCostType purchaseOrderCost;
    protected FinanicalAmountType freightOnBoardCost;
    protected FinanicalAmountType averageFreightCost;
    protected FinanicalAmountType estimatedLandedCost;
    protected Boolean priceProtectionEnabled;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar effectiveDate;
    protected String systemClassifier;

    /**
     * Gets the value of the purchaseOrderCost property.
     * 
     * @return
     *     possible object is
     *     {@link PurchaseOrderCostType }
     *     
     */
    public PurchaseOrderCostType getPurchaseOrderCost() {
        return purchaseOrderCost;
    }

    /**
     * Sets the value of the purchaseOrderCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link PurchaseOrderCostType }
     *     
     */
    public void setPurchaseOrderCost(PurchaseOrderCostType value) {
        this.purchaseOrderCost = value;
    }

    /**
     * Gets the value of the freightOnBoardCost property.
     * 
     * @return
     *     possible object is
     *     {@link FinanicalAmountType }
     *     
     */
    public FinanicalAmountType getFreightOnBoardCost() {
        return freightOnBoardCost;
    }

    /**
     * Sets the value of the freightOnBoardCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link FinanicalAmountType }
     *     
     */
    public void setFreightOnBoardCost(FinanicalAmountType value) {
        this.freightOnBoardCost = value;
    }

    /**
     * Gets the value of the averageFreightCost property.
     * 
     * @return
     *     possible object is
     *     {@link FinanicalAmountType }
     *     
     */
    public FinanicalAmountType getAverageFreightCost() {
        return averageFreightCost;
    }

    /**
     * Sets the value of the averageFreightCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link FinanicalAmountType }
     *     
     */
    public void setAverageFreightCost(FinanicalAmountType value) {
        this.averageFreightCost = value;
    }

    /**
     * Gets the value of the estimatedLandedCost property.
     * 
     * @return
     *     possible object is
     *     {@link FinanicalAmountType }
     *     
     */
    public FinanicalAmountType getEstimatedLandedCost() {
        return estimatedLandedCost;
    }

    /**
     * Sets the value of the estimatedLandedCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link FinanicalAmountType }
     *     
     */
    public void setEstimatedLandedCost(FinanicalAmountType value) {
        this.estimatedLandedCost = value;
    }

    /**
     * Gets the value of the priceProtectionEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPriceProtectionEnabled() {
        return priceProtectionEnabled;
    }

    /**
     * Sets the value of the priceProtectionEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPriceProtectionEnabled(Boolean value) {
        this.priceProtectionEnabled = value;
    }

    /**
     * Gets the value of the effectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * Sets the value of the effectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEffectiveDate(XMLGregorianCalendar value) {
        this.effectiveDate = value;
    }

    /**
     * Gets the value of the systemClassifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystemClassifier() {
        return systemClassifier;
    }

    /**
     * Sets the value of the systemClassifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystemClassifier(String value) {
        this.systemClassifier = value;
    }

}
