//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 10:48:26 AM CDT 
//


package com.officedepot;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Represents Sku Department Markup Details
 * 			
 * 
 * <p>Java class for DapartmentMarkupType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DapartmentMarkupType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="retailMarkupPercent" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="costMarkupPercent" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="markupCalculationType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DapartmentMarkupType", namespace = "http://eai.officedepot.com/model/Inventory", propOrder = {
    "retailMarkupPercent",
    "costMarkupPercent",
    "markupCalculationType"
})
public class DapartmentMarkupType {

    protected BigDecimal retailMarkupPercent;
    protected BigDecimal costMarkupPercent;
    protected String markupCalculationType;

    /**
     * Gets the value of the retailMarkupPercent property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRetailMarkupPercent() {
        return retailMarkupPercent;
    }

    /**
     * Sets the value of the retailMarkupPercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRetailMarkupPercent(BigDecimal value) {
        this.retailMarkupPercent = value;
    }

    /**
     * Gets the value of the costMarkupPercent property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCostMarkupPercent() {
        return costMarkupPercent;
    }

    /**
     * Sets the value of the costMarkupPercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCostMarkupPercent(BigDecimal value) {
        this.costMarkupPercent = value;
    }

    /**
     * Gets the value of the markupCalculationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarkupCalculationType() {
        return markupCalculationType;
    }

    /**
     * Sets the value of the markupCalculationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarkupCalculationType(String value) {
        this.markupCalculationType = value;
    }

}
