//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 10:48:26 AM CDT 
//


package com.officedepot;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Represents Sku Department Planning Indicators
 * 
 * <p>Java class for DepartmentPlanningIndicatorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DepartmentPlanningIndicatorType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="vatIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="planIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="forecastIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="nonCodeIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="productProtectionIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DepartmentPlanningIndicatorType", namespace = "http://eai.officedepot.com/model/Inventory", propOrder = {
    "vatIndicator",
    "planIndicator",
    "forecastIndicator",
    "nonCodeIndicator",
    "productProtectionIndicator"
})
public class DepartmentPlanningIndicatorType {

    protected String vatIndicator;
    protected String planIndicator;
    protected String forecastIndicator;
    protected String nonCodeIndicator;
    protected String productProtectionIndicator;

    /**
     * Gets the value of the vatIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVatIndicator() {
        return vatIndicator;
    }

    /**
     * Sets the value of the vatIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVatIndicator(String value) {
        this.vatIndicator = value;
    }

    /**
     * Gets the value of the planIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlanIndicator() {
        return planIndicator;
    }

    /**
     * Sets the value of the planIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanIndicator(String value) {
        this.planIndicator = value;
    }

    /**
     * Gets the value of the forecastIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForecastIndicator() {
        return forecastIndicator;
    }

    /**
     * Sets the value of the forecastIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForecastIndicator(String value) {
        this.forecastIndicator = value;
    }

    /**
     * Gets the value of the nonCodeIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNonCodeIndicator() {
        return nonCodeIndicator;
    }

    /**
     * Sets the value of the nonCodeIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNonCodeIndicator(String value) {
        this.nonCodeIndicator = value;
    }

    /**
     * Gets the value of the productProtectionIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductProtectionIndicator() {
        return productProtectionIndicator;
    }

    /**
     * Sets the value of the productProtectionIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductProtectionIndicator(String value) {
        this.productProtectionIndicator = value;
    }

}
