//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 10:48:26 AM CDT 
//


package com.officedepot;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Dimension properties
 * 
 * <p>Java class for DimensionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DimensionType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="length" type="{http://eai.officedepot.com/model/ODCommon}BaseMeasurementType" minOccurs="0"/&gt;
 *         &lt;element name="width" type="{http://eai.officedepot.com/model/ODCommon}BaseMeasurementType" minOccurs="0"/&gt;
 *         &lt;element name="height" type="{http://eai.officedepot.com/model/ODCommon}BaseMeasurementType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DimensionType", propOrder = {
    "length",
    "width",
    "height"
})
public class DimensionType {

    protected BaseMeasurementType length;
    protected BaseMeasurementType width;
    protected BaseMeasurementType height;

    /**
     * Gets the value of the length property.
     * 
     * @return
     *     possible object is
     *     {@link BaseMeasurementType }
     *     
     */
    public BaseMeasurementType getLength() {
        return length;
    }

    /**
     * Sets the value of the length property.
     * 
     * @param value
     *     allowed object is
     *     {@link BaseMeasurementType }
     *     
     */
    public void setLength(BaseMeasurementType value) {
        this.length = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link BaseMeasurementType }
     *     
     */
    public BaseMeasurementType getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link BaseMeasurementType }
     *     
     */
    public void setWidth(BaseMeasurementType value) {
        this.width = value;
    }

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link BaseMeasurementType }
     *     
     */
    public BaseMeasurementType getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link BaseMeasurementType }
     *     
     */
    public void setHeight(BaseMeasurementType value) {
        this.height = value;
    }

}
