//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 10:48:26 AM CDT 
//


package com.officedepot;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This is the base internal Transaction type, from
 * 				which others extend.
 * 
 * <p>Java class for InternalTransactionHeaderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InternalTransactionHeaderType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="consumer" type="{http://www.officedepot.com/model/transaction}ConsumerType"/&gt;
 *         &lt;element name="serviceBus" type="{http://www.officedepot.com/model/transaction}ServiceBusType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InternalTransactionHeaderType", namespace = "http://www.officedepot.com/model/transaction", propOrder = {
    "consumer",
    "serviceBus"
})
public class InternalTransactionHeaderType {

    @XmlElement(required = true)
    protected ConsumerType consumer;
    protected ServiceBusType serviceBus;

    /**
     * Gets the value of the consumer property.
     * 
     * @return
     *     possible object is
     *     {@link ConsumerType }
     *     
     */
    public ConsumerType getConsumer() {
        return consumer;
    }

    /**
     * Sets the value of the consumer property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConsumerType }
     *     
     */
    public void setConsumer(ConsumerType value) {
        this.consumer = value;
    }

    /**
     * Gets the value of the serviceBus property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceBusType }
     *     
     */
    public ServiceBusType getServiceBus() {
        return serviceBus;
    }

    /**
     * Sets the value of the serviceBus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceBusType }
     *     
     */
    public void setServiceBus(ServiceBusType value) {
        this.serviceBus = value;
    }

}
