//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 10:48:26 AM CDT 
//


package com.officedepot;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for KitComponentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="KitComponentType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://eai.officedepot.com/model/Inventory}SkuDetailsType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="kitItem" type="{http://eai.officedepot.com/model/Inventory}SkuIdType" minOccurs="0"/&gt;
 *         &lt;element name="kitType" type="{http://eai.officedepot.com/model/Inventory}KitTypeType" minOccurs="0"/&gt;
 *         &lt;element name="componentType" type="{http://eai.officedepot.com/model/Inventory}ComponentTypeType" minOccurs="0"/&gt;
 *         &lt;element name="componentValue" type="{http://eai.officedepot.com/model/Inventory}ComponentValueType" minOccurs="0"/&gt;
 *         &lt;element name="quantity" type="{http://eai.officedepot.com/model/ODCommon}QuantityType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "KitComponentType", namespace = "http://eai.officedepot.com/model/Inventory", propOrder = {
    "kitItem",
    "kitType",
    "componentType",
    "componentValue",
    "quantity"
})
public class KitComponentType
    extends SkuDetailsType
{

    protected String kitItem;
    protected String kitType;
    protected String componentType;
    protected String componentValue;
    protected BigInteger quantity;

    /**
     * Gets the value of the kitItem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKitItem() {
        return kitItem;
    }

    /**
     * Sets the value of the kitItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKitItem(String value) {
        this.kitItem = value;
    }

    /**
     * Gets the value of the kitType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKitType() {
        return kitType;
    }

    /**
     * Sets the value of the kitType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKitType(String value) {
        this.kitType = value;
    }

    /**
     * Gets the value of the componentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComponentType() {
        return componentType;
    }

    /**
     * Sets the value of the componentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComponentType(String value) {
        this.componentType = value;
    }

    /**
     * Gets the value of the componentValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComponentValue() {
        return componentValue;
    }

    /**
     * Sets the value of the componentValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComponentValue(String value) {
        this.componentValue = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setQuantity(BigInteger value) {
        this.quantity = value;
    }

}
