//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 10:48:26 AM CDT 
//


package com.officedepot;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Identifies the payment term of the associated entity
 * 
 * <p>Java class for PaymentTermType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PaymentTermType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="paymentTermId" type="{http://eai.officedepot.com/model/ODCommon}PaymentTermIdType" minOccurs="0"/&gt;
 *         &lt;element name="paymentTermCode" type="{http://eai.officedepot.com/model/ODCommon}PaymentTermCodeType" minOccurs="0"/&gt;
 *         &lt;element name="paymentGroup" type="{http://eai.officedepot.com/model/ODCommon}PaymentGroupType" minOccurs="0"/&gt;
 *         &lt;element name="paymentBasisCode" type="{http://eai.officedepot.com/model/ODCommon}PaymentBasisCodeType" minOccurs="0"/&gt;
 *         &lt;element name="paymentDuration" type="{http://eai.officedepot.com/model/ODCommon}PaymentDurationType" minOccurs="0"/&gt;
 *         &lt;element name="paymentFrequency" type="{http://eai.officedepot.com/model/ODCommon}PaymentFrequencyType" minOccurs="0"/&gt;
 *         &lt;element name="discount" type="{http://eai.officedepot.com/model/ODCommon}PercentType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PaymentTermType", propOrder = {
    "paymentTermId",
    "paymentTermCode",
    "paymentGroup",
    "paymentBasisCode",
    "paymentDuration",
    "paymentFrequency",
    "discount"
})
public class PaymentTermType {

    protected String paymentTermId;
    protected String paymentTermCode;
    protected String paymentGroup;
    protected String paymentBasisCode;
    protected String paymentDuration;
    protected String paymentFrequency;
    protected Double discount;

    /**
     * Gets the value of the paymentTermId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentTermId() {
        return paymentTermId;
    }

    /**
     * Sets the value of the paymentTermId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentTermId(String value) {
        this.paymentTermId = value;
    }

    /**
     * Gets the value of the paymentTermCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentTermCode() {
        return paymentTermCode;
    }

    /**
     * Sets the value of the paymentTermCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentTermCode(String value) {
        this.paymentTermCode = value;
    }

    /**
     * Gets the value of the paymentGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentGroup() {
        return paymentGroup;
    }

    /**
     * Sets the value of the paymentGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentGroup(String value) {
        this.paymentGroup = value;
    }

    /**
     * Gets the value of the paymentBasisCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentBasisCode() {
        return paymentBasisCode;
    }

    /**
     * Sets the value of the paymentBasisCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentBasisCode(String value) {
        this.paymentBasisCode = value;
    }

    /**
     * Gets the value of the paymentDuration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentDuration() {
        return paymentDuration;
    }

    /**
     * Sets the value of the paymentDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentDuration(String value) {
        this.paymentDuration = value;
    }

    /**
     * Gets the value of the paymentFrequency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentFrequency() {
        return paymentFrequency;
    }

    /**
     * Sets the value of the paymentFrequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentFrequency(String value) {
        this.paymentFrequency = value;
    }

    /**
     * Gets the value of the discount property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getDiscount() {
        return discount;
    }

    /**
     * Sets the value of the discount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDiscount(Double value) {
        this.discount = value;
    }

}
