//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 10:48:26 AM CDT 
//


package com.officedepot;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PersonDemographicType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PersonDemographicType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ssn" type="{http://eai.officedepot.com/model/ODCommon}SSNType" minOccurs="0"/&gt;
 *         &lt;element name="annualIncome" type="{http://eai.officedepot.com/model/ODCommon}AmountType" minOccurs="0"/&gt;
 *         &lt;element name="otherAnnualIncomeAmount" type="{http://eai.officedepot.com/model/ODCommon}AmountType" minOccurs="0"/&gt;
 *         &lt;element name="housing" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="monthlyRent" type="{http://eai.officedepot.com/model/ODCommon}AmountType" minOccurs="0"/&gt;
 *                   &lt;element name="rentOrOwn" type="{http://eai.officedepot.com/model/ODCommon}RentOrOwnType" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="photoIdDetails" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="photoIdNumber" type="{http://eai.officedepot.com/model/ODCommon}PhotoIdNumberType" minOccurs="0"/&gt;
 *                   &lt;element name="photoIdStateCode" type="{http://eai.officedepot.com/model/ODCommon}StateAbrType" minOccurs="0"/&gt;
 *                   &lt;element name="photoIdType" type="{http://eai.officedepot.com/model/ODCommon}PhotoIdTypeType" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PersonDemographicType", propOrder = {
    "ssn",
    "annualIncome",
    "otherAnnualIncomeAmount",
    "housing",
    "photoIdDetails"
})
public class PersonDemographicType {

    protected String ssn;
    protected Double annualIncome;
    protected Double otherAnnualIncomeAmount;
    protected PersonDemographicType.Housing housing;
    protected PersonDemographicType.PhotoIdDetails photoIdDetails;

    /**
     * Gets the value of the ssn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSsn() {
        return ssn;
    }

    /**
     * Sets the value of the ssn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSsn(String value) {
        this.ssn = value;
    }

    /**
     * Gets the value of the annualIncome property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getAnnualIncome() {
        return annualIncome;
    }

    /**
     * Sets the value of the annualIncome property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setAnnualIncome(Double value) {
        this.annualIncome = value;
    }

    /**
     * Gets the value of the otherAnnualIncomeAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getOtherAnnualIncomeAmount() {
        return otherAnnualIncomeAmount;
    }

    /**
     * Sets the value of the otherAnnualIncomeAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setOtherAnnualIncomeAmount(Double value) {
        this.otherAnnualIncomeAmount = value;
    }

    /**
     * Gets the value of the housing property.
     * 
     * @return
     *     possible object is
     *     {@link PersonDemographicType.Housing }
     *     
     */
    public PersonDemographicType.Housing getHousing() {
        return housing;
    }

    /**
     * Sets the value of the housing property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonDemographicType.Housing }
     *     
     */
    public void setHousing(PersonDemographicType.Housing value) {
        this.housing = value;
    }

    /**
     * Gets the value of the photoIdDetails property.
     * 
     * @return
     *     possible object is
     *     {@link PersonDemographicType.PhotoIdDetails }
     *     
     */
    public PersonDemographicType.PhotoIdDetails getPhotoIdDetails() {
        return photoIdDetails;
    }

    /**
     * Sets the value of the photoIdDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonDemographicType.PhotoIdDetails }
     *     
     */
    public void setPhotoIdDetails(PersonDemographicType.PhotoIdDetails value) {
        this.photoIdDetails = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="monthlyRent" type="{http://eai.officedepot.com/model/ODCommon}AmountType" minOccurs="0"/&gt;
     *         &lt;element name="rentOrOwn" type="{http://eai.officedepot.com/model/ODCommon}RentOrOwnType" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "monthlyRent",
        "rentOrOwn"
    })
    public static class Housing {

        protected Double monthlyRent;
        @XmlSchemaType(name = "string")
        protected RentOrOwnType rentOrOwn;

        /**
         * Gets the value of the monthlyRent property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getMonthlyRent() {
            return monthlyRent;
        }

        /**
         * Sets the value of the monthlyRent property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setMonthlyRent(Double value) {
            this.monthlyRent = value;
        }

        /**
         * Gets the value of the rentOrOwn property.
         * 
         * @return
         *     possible object is
         *     {@link RentOrOwnType }
         *     
         */
        public RentOrOwnType getRentOrOwn() {
            return rentOrOwn;
        }

        /**
         * Sets the value of the rentOrOwn property.
         * 
         * @param value
         *     allowed object is
         *     {@link RentOrOwnType }
         *     
         */
        public void setRentOrOwn(RentOrOwnType value) {
            this.rentOrOwn = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="photoIdNumber" type="{http://eai.officedepot.com/model/ODCommon}PhotoIdNumberType" minOccurs="0"/&gt;
     *         &lt;element name="photoIdStateCode" type="{http://eai.officedepot.com/model/ODCommon}StateAbrType" minOccurs="0"/&gt;
     *         &lt;element name="photoIdType" type="{http://eai.officedepot.com/model/ODCommon}PhotoIdTypeType" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "photoIdNumber",
        "photoIdStateCode",
        "photoIdType"
    })
    public static class PhotoIdDetails {

        protected String photoIdNumber;
        protected String photoIdStateCode;
        protected String photoIdType;

        /**
         * Gets the value of the photoIdNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPhotoIdNumber() {
            return photoIdNumber;
        }

        /**
         * Sets the value of the photoIdNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPhotoIdNumber(String value) {
            this.photoIdNumber = value;
        }

        /**
         * Gets the value of the photoIdStateCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPhotoIdStateCode() {
            return photoIdStateCode;
        }

        /**
         * Sets the value of the photoIdStateCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPhotoIdStateCode(String value) {
            this.photoIdStateCode = value;
        }

        /**
         * Gets the value of the photoIdType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPhotoIdType() {
            return photoIdType;
        }

        /**
         * Sets the value of the photoIdType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPhotoIdType(String value) {
            this.photoIdType = value;
        }

    }

}
