//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 10:48:26 AM CDT 
//


package com.officedepot;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RetailChannelType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RetailChannelType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="STORE"/&gt;
 *     &lt;enumeration value="ONLINE_DIRECT"/&gt;
 *     &lt;enumeration value="ONLINE_BSD"/&gt;
 *     &lt;enumeration value="ONLINE"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "RetailChannelType")
@XmlEnum
public enum RetailChannelType {

    STORE,
    ONLINE_DIRECT,
    ONLINE_BSD,
    ONLINE;

    public String value() {
        return name();
    }

    public static RetailChannelType fromValue(String v) {
        return valueOf(v);
    }

}
