//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 10:48:26 AM CDT 
//


package com.officedepot;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * This is an extension of the ServiceBusType that
 * 				includes historical transaction headers
 * 
 * <p>Java class for ServiceBusHistoryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceBusHistoryType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.officedepot.com/model/transaction}ServiceBusType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="history" type="{http://www.officedepot.com/model/transaction}TransactionHistoryType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceBusHistoryType", namespace = "http://www.officedepot.com/model/transaction", propOrder = {
    "history"
})
public class ServiceBusHistoryType
    extends ServiceBusType
{

    protected TransactionHistoryType history;

    /**
     * Gets the value of the history property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionHistoryType }
     *     
     */
    public TransactionHistoryType getHistory() {
        return history;
    }

    /**
     * Sets the value of the history property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionHistoryType }
     *     
     */
    public void setHistory(TransactionHistoryType value) {
        this.history = value;
    }

}
