//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 10:48:26 AM CDT 
//


package com.officedepot;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Represents Sku Class Details
 * 
 * <p>Java class for SkuClassDetailType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SkuClassDetailType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="classCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="className" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="parentDepartment" type="{http://eai.officedepot.com/model/Inventory}SkuDepartmentDetailType" minOccurs="0"/&gt;
 *         &lt;element name="classVATIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="automaticMarkdownDays" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="fifthMArkdownProcessCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="priceZone" type="{http://eai.officedepot.com/model/Inventory}PriceZoneType" minOccurs="0"/&gt;
 *         &lt;element name="highValue" type="{http://eai.officedepot.com/model/ODCommon}KeyValuePairType" minOccurs="0"/&gt;
 *         &lt;element name="reportingSortOrder" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="tier1PriceMatchFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="merchantAutoApproveFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="furnitureFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SkuClassDetailType", namespace = "http://eai.officedepot.com/model/Inventory", propOrder = {
    "classCode",
    "className",
    "parentDepartment",
    "classVATIndicator",
    "automaticMarkdownDays",
    "fifthMArkdownProcessCode",
    "priceZone",
    "highValue",
    "reportingSortOrder",
    "tier1PriceMatchFlag",
    "merchantAutoApproveFlag",
    "furnitureFlag"
})
@XmlSeeAlso({
    SkuSubClassDetailType.class
})
public class SkuClassDetailType {

    protected String classCode;
    protected String className;
    protected SkuDepartmentDetailType parentDepartment;
    protected String classVATIndicator;
    protected String automaticMarkdownDays;
    protected String fifthMArkdownProcessCode;
    protected PriceZoneType priceZone;
    protected KeyValuePairType highValue;
    protected String reportingSortOrder;
    protected String tier1PriceMatchFlag;
    protected String merchantAutoApproveFlag;
    protected String furnitureFlag;

    /**
     * Gets the value of the classCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassCode() {
        return classCode;
    }

    /**
     * Sets the value of the classCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassCode(String value) {
        this.classCode = value;
    }

    /**
     * Gets the value of the className property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassName() {
        return className;
    }

    /**
     * Sets the value of the className property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassName(String value) {
        this.className = value;
    }

    /**
     * Gets the value of the parentDepartment property.
     * 
     * @return
     *     possible object is
     *     {@link SkuDepartmentDetailType }
     *     
     */
    public SkuDepartmentDetailType getParentDepartment() {
        return parentDepartment;
    }

    /**
     * Sets the value of the parentDepartment property.
     * 
     * @param value
     *     allowed object is
     *     {@link SkuDepartmentDetailType }
     *     
     */
    public void setParentDepartment(SkuDepartmentDetailType value) {
        this.parentDepartment = value;
    }

    /**
     * Gets the value of the classVATIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassVATIndicator() {
        return classVATIndicator;
    }

    /**
     * Sets the value of the classVATIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassVATIndicator(String value) {
        this.classVATIndicator = value;
    }

    /**
     * Gets the value of the automaticMarkdownDays property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutomaticMarkdownDays() {
        return automaticMarkdownDays;
    }

    /**
     * Sets the value of the automaticMarkdownDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutomaticMarkdownDays(String value) {
        this.automaticMarkdownDays = value;
    }

    /**
     * Gets the value of the fifthMArkdownProcessCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFifthMArkdownProcessCode() {
        return fifthMArkdownProcessCode;
    }

    /**
     * Sets the value of the fifthMArkdownProcessCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFifthMArkdownProcessCode(String value) {
        this.fifthMArkdownProcessCode = value;
    }

    /**
     * Gets the value of the priceZone property.
     * 
     * @return
     *     possible object is
     *     {@link PriceZoneType }
     *     
     */
    public PriceZoneType getPriceZone() {
        return priceZone;
    }

    /**
     * Sets the value of the priceZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceZoneType }
     *     
     */
    public void setPriceZone(PriceZoneType value) {
        this.priceZone = value;
    }

    /**
     * Gets the value of the highValue property.
     * 
     * @return
     *     possible object is
     *     {@link KeyValuePairType }
     *     
     */
    public KeyValuePairType getHighValue() {
        return highValue;
    }

    /**
     * Sets the value of the highValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeyValuePairType }
     *     
     */
    public void setHighValue(KeyValuePairType value) {
        this.highValue = value;
    }

    /**
     * Gets the value of the reportingSortOrder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportingSortOrder() {
        return reportingSortOrder;
    }

    /**
     * Sets the value of the reportingSortOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportingSortOrder(String value) {
        this.reportingSortOrder = value;
    }

    /**
     * Gets the value of the tier1PriceMatchFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTier1PriceMatchFlag() {
        return tier1PriceMatchFlag;
    }

    /**
     * Sets the value of the tier1PriceMatchFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTier1PriceMatchFlag(String value) {
        this.tier1PriceMatchFlag = value;
    }

    /**
     * Gets the value of the merchantAutoApproveFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantAutoApproveFlag() {
        return merchantAutoApproveFlag;
    }

    /**
     * Sets the value of the merchantAutoApproveFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantAutoApproveFlag(String value) {
        this.merchantAutoApproveFlag = value;
    }

    /**
     * Gets the value of the furnitureFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFurnitureFlag() {
        return furnitureFlag;
    }

    /**
     * Sets the value of the furnitureFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFurnitureFlag(String value) {
        this.furnitureFlag = value;
    }

}
