//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 10:48:26 AM CDT 
//


package com.officedepot;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Information regarding the Sku
 * 			
 * 
 * <p>Java class for SkuDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SkuDetailsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://eai.officedepot.com/model/Inventory}SkuType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="skuBrand" type="{http://eai.officedepot.com/model/Inventory}SkuBrandType" minOccurs="0"/&gt;
 *         &lt;element name="skuProduct" type="{http://eai.officedepot.com/model/Inventory}SkuProductType" minOccurs="0"/&gt;
 *         &lt;element name="skuClass" type="{http://eai.officedepot.com/model/Inventory}SkuClassType" minOccurs="0"/&gt;
 *         &lt;element name="skuSubclass" type="{http://eai.officedepot.com/model/Inventory}SkuSubclassType" minOccurs="0"/&gt;
 *         &lt;element name="skuPrivateLabel" type="{http://eai.officedepot.com/model/Inventory}SkuPrivateLabelType" minOccurs="0"/&gt;
 *         &lt;element name="mobileDeviceSkuAttributes" type="{http://eai.officedepot.com/model/Inventory}SkuMobileDeviceAttributesType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SkuDetailsType", namespace = "http://eai.officedepot.com/model/Inventory", propOrder = {
    "skuBrand",
    "skuProduct",
    "skuClass",
    "skuSubclass",
    "skuPrivateLabel",
    "mobileDeviceSkuAttributes"
})
@XmlSeeAlso({
    KitType.class,
    KitComponentType.class
})
public class SkuDetailsType
    extends SkuType
{

    protected String skuBrand;
    protected String skuProduct;
    protected String skuClass;
    protected String skuSubclass;
    protected String skuPrivateLabel;
    protected SkuMobileDeviceAttributesType mobileDeviceSkuAttributes;

    /**
     * Gets the value of the skuBrand property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSkuBrand() {
        return skuBrand;
    }

    /**
     * Sets the value of the skuBrand property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSkuBrand(String value) {
        this.skuBrand = value;
    }

    /**
     * Gets the value of the skuProduct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSkuProduct() {
        return skuProduct;
    }

    /**
     * Sets the value of the skuProduct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSkuProduct(String value) {
        this.skuProduct = value;
    }

    /**
     * Gets the value of the skuClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSkuClass() {
        return skuClass;
    }

    /**
     * Sets the value of the skuClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSkuClass(String value) {
        this.skuClass = value;
    }

    /**
     * Gets the value of the skuSubclass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSkuSubclass() {
        return skuSubclass;
    }

    /**
     * Sets the value of the skuSubclass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSkuSubclass(String value) {
        this.skuSubclass = value;
    }

    /**
     * Gets the value of the skuPrivateLabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSkuPrivateLabel() {
        return skuPrivateLabel;
    }

    /**
     * Sets the value of the skuPrivateLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSkuPrivateLabel(String value) {
        this.skuPrivateLabel = value;
    }

    /**
     * Gets the value of the mobileDeviceSkuAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link SkuMobileDeviceAttributesType }
     *     
     */
    public SkuMobileDeviceAttributesType getMobileDeviceSkuAttributes() {
        return mobileDeviceSkuAttributes;
    }

    /**
     * Sets the value of the mobileDeviceSkuAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link SkuMobileDeviceAttributesType }
     *     
     */
    public void setMobileDeviceSkuAttributes(SkuMobileDeviceAttributesType value) {
        this.mobileDeviceSkuAttributes = value;
    }

}
