//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 10:48:26 AM CDT 
//


package com.officedepot;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Represents Sku Department Details
 * 
 * <p>Java class for SkuDepartmentDetailType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SkuDepartmentDetailType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="departmentCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="departmentName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="parentGroup" type="{http://eai.officedepot.com/model/Inventory}SkuGroupDetailType" minOccurs="0"/&gt;
 *         &lt;element name="profitCalculationType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="openToBuyCalculationType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="purchaseType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="departmentMarkup" type="{http://eai.officedepot.com/model/Inventory}DapartmentMarkupType" minOccurs="0"/&gt;
 *         &lt;element name="departmentPlanningIndicator" type="{http://eai.officedepot.com/model/Inventory}DepartmentPlanningIndicatorType" minOccurs="0"/&gt;
 *         &lt;element name="totalMarketAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="maximumAverageCounter" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="averageTolerancePercent" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="tdcPoVariancePercent" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="tdcNetVariancePercent" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="reportingSortOrder" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="gsFurnitureFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="segmentationFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SkuDepartmentDetailType", namespace = "http://eai.officedepot.com/model/Inventory", propOrder = {
    "departmentCode",
    "departmentName",
    "parentGroup",
    "profitCalculationType",
    "openToBuyCalculationType",
    "purchaseType",
    "departmentMarkup",
    "departmentPlanningIndicator",
    "totalMarketAmount",
    "maximumAverageCounter",
    "averageTolerancePercent",
    "tdcPoVariancePercent",
    "tdcNetVariancePercent",
    "reportingSortOrder",
    "gsFurnitureFlag",
    "segmentationFlag"
})
public class SkuDepartmentDetailType {

    protected String departmentCode;
    protected String departmentName;
    protected SkuGroupDetailType parentGroup;
    protected String profitCalculationType;
    protected String openToBuyCalculationType;
    protected String purchaseType;
    protected DapartmentMarkupType departmentMarkup;
    protected DepartmentPlanningIndicatorType departmentPlanningIndicator;
    protected BigDecimal totalMarketAmount;
    protected BigDecimal maximumAverageCounter;
    protected BigDecimal averageTolerancePercent;
    protected String tdcPoVariancePercent;
    protected String tdcNetVariancePercent;
    protected String reportingSortOrder;
    protected String gsFurnitureFlag;
    protected String segmentationFlag;

    /**
     * Gets the value of the departmentCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartmentCode() {
        return departmentCode;
    }

    /**
     * Sets the value of the departmentCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartmentCode(String value) {
        this.departmentCode = value;
    }

    /**
     * Gets the value of the departmentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * Sets the value of the departmentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartmentName(String value) {
        this.departmentName = value;
    }

    /**
     * Gets the value of the parentGroup property.
     * 
     * @return
     *     possible object is
     *     {@link SkuGroupDetailType }
     *     
     */
    public SkuGroupDetailType getParentGroup() {
        return parentGroup;
    }

    /**
     * Sets the value of the parentGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link SkuGroupDetailType }
     *     
     */
    public void setParentGroup(SkuGroupDetailType value) {
        this.parentGroup = value;
    }

    /**
     * Gets the value of the profitCalculationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfitCalculationType() {
        return profitCalculationType;
    }

    /**
     * Sets the value of the profitCalculationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfitCalculationType(String value) {
        this.profitCalculationType = value;
    }

    /**
     * Gets the value of the openToBuyCalculationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpenToBuyCalculationType() {
        return openToBuyCalculationType;
    }

    /**
     * Sets the value of the openToBuyCalculationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpenToBuyCalculationType(String value) {
        this.openToBuyCalculationType = value;
    }

    /**
     * Gets the value of the purchaseType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPurchaseType() {
        return purchaseType;
    }

    /**
     * Sets the value of the purchaseType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPurchaseType(String value) {
        this.purchaseType = value;
    }

    /**
     * Gets the value of the departmentMarkup property.
     * 
     * @return
     *     possible object is
     *     {@link DapartmentMarkupType }
     *     
     */
    public DapartmentMarkupType getDepartmentMarkup() {
        return departmentMarkup;
    }

    /**
     * Sets the value of the departmentMarkup property.
     * 
     * @param value
     *     allowed object is
     *     {@link DapartmentMarkupType }
     *     
     */
    public void setDepartmentMarkup(DapartmentMarkupType value) {
        this.departmentMarkup = value;
    }

    /**
     * Gets the value of the departmentPlanningIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link DepartmentPlanningIndicatorType }
     *     
     */
    public DepartmentPlanningIndicatorType getDepartmentPlanningIndicator() {
        return departmentPlanningIndicator;
    }

    /**
     * Sets the value of the departmentPlanningIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link DepartmentPlanningIndicatorType }
     *     
     */
    public void setDepartmentPlanningIndicator(DepartmentPlanningIndicatorType value) {
        this.departmentPlanningIndicator = value;
    }

    /**
     * Gets the value of the totalMarketAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalMarketAmount() {
        return totalMarketAmount;
    }

    /**
     * Sets the value of the totalMarketAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalMarketAmount(BigDecimal value) {
        this.totalMarketAmount = value;
    }

    /**
     * Gets the value of the maximumAverageCounter property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMaximumAverageCounter() {
        return maximumAverageCounter;
    }

    /**
     * Sets the value of the maximumAverageCounter property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMaximumAverageCounter(BigDecimal value) {
        this.maximumAverageCounter = value;
    }

    /**
     * Gets the value of the averageTolerancePercent property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAverageTolerancePercent() {
        return averageTolerancePercent;
    }

    /**
     * Sets the value of the averageTolerancePercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAverageTolerancePercent(BigDecimal value) {
        this.averageTolerancePercent = value;
    }

    /**
     * Gets the value of the tdcPoVariancePercent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTdcPoVariancePercent() {
        return tdcPoVariancePercent;
    }

    /**
     * Sets the value of the tdcPoVariancePercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTdcPoVariancePercent(String value) {
        this.tdcPoVariancePercent = value;
    }

    /**
     * Gets the value of the tdcNetVariancePercent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTdcNetVariancePercent() {
        return tdcNetVariancePercent;
    }

    /**
     * Sets the value of the tdcNetVariancePercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTdcNetVariancePercent(String value) {
        this.tdcNetVariancePercent = value;
    }

    /**
     * Gets the value of the reportingSortOrder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportingSortOrder() {
        return reportingSortOrder;
    }

    /**
     * Sets the value of the reportingSortOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportingSortOrder(String value) {
        this.reportingSortOrder = value;
    }

    /**
     * Gets the value of the gsFurnitureFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGsFurnitureFlag() {
        return gsFurnitureFlag;
    }

    /**
     * Sets the value of the gsFurnitureFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGsFurnitureFlag(String value) {
        this.gsFurnitureFlag = value;
    }

    /**
     * Gets the value of the segmentationFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSegmentationFlag() {
        return segmentationFlag;
    }

    /**
     * Sets the value of the segmentationFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSegmentationFlag(String value) {
        this.segmentationFlag = value;
    }

}
