//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 10:48:26 AM CDT 
//


package com.officedepot;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Represents Sku Sub Class Details
 * 
 * <p>Java class for SkuSubClassDetailType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SkuSubClassDetailType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://eai.officedepot.com/model/Inventory}SkuClassDetailType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="subClassCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="subClassName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="parentClass" type="{http://eai.officedepot.com/model/Inventory}SkuClassDetailType" minOccurs="0"/&gt;
 *         &lt;element name="defaultTaxCategory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="globalContentIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="consumableGoodsIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="taxableIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="deliveryThreshold" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="mpnIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="accessoryIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="alternateSubstituteIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="quoteableFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="displaySkuFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="misshipFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="procurementCalculationFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SkuSubClassDetailType", namespace = "http://eai.officedepot.com/model/Inventory", propOrder = {
    "subClassCode",
    "subClassName",
    "parentClass",
    "defaultTaxCategory",
    "globalContentIndicator",
    "consumableGoodsIndicator",
    "taxableIndicator",
    "deliveryThreshold",
    "mpnIndicator",
    "accessoryIndicator",
    "alternateSubstituteIndicator",
    "quoteableFlag",
    "displaySkuFlag",
    "misshipFlag",
    "procurementCalculationFlag"
})
public class SkuSubClassDetailType
    extends SkuClassDetailType
{

    protected String subClassCode;
    protected String subClassName;
    protected SkuClassDetailType parentClass;
    protected String defaultTaxCategory;
    protected String globalContentIndicator;
    protected String consumableGoodsIndicator;
    protected String taxableIndicator;
    protected String deliveryThreshold;
    protected String mpnIndicator;
    protected String accessoryIndicator;
    protected String alternateSubstituteIndicator;
    protected String quoteableFlag;
    protected String displaySkuFlag;
    protected String misshipFlag;
    protected String procurementCalculationFlag;

    /**
     * Gets the value of the subClassCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubClassCode() {
        return subClassCode;
    }

    /**
     * Sets the value of the subClassCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubClassCode(String value) {
        this.subClassCode = value;
    }

    /**
     * Gets the value of the subClassName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubClassName() {
        return subClassName;
    }

    /**
     * Sets the value of the subClassName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubClassName(String value) {
        this.subClassName = value;
    }

    /**
     * Gets the value of the parentClass property.
     * 
     * @return
     *     possible object is
     *     {@link SkuClassDetailType }
     *     
     */
    public SkuClassDetailType getParentClass() {
        return parentClass;
    }

    /**
     * Sets the value of the parentClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link SkuClassDetailType }
     *     
     */
    public void setParentClass(SkuClassDetailType value) {
        this.parentClass = value;
    }

    /**
     * Gets the value of the defaultTaxCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultTaxCategory() {
        return defaultTaxCategory;
    }

    /**
     * Sets the value of the defaultTaxCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultTaxCategory(String value) {
        this.defaultTaxCategory = value;
    }

    /**
     * Gets the value of the globalContentIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGlobalContentIndicator() {
        return globalContentIndicator;
    }

    /**
     * Sets the value of the globalContentIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGlobalContentIndicator(String value) {
        this.globalContentIndicator = value;
    }

    /**
     * Gets the value of the consumableGoodsIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsumableGoodsIndicator() {
        return consumableGoodsIndicator;
    }

    /**
     * Sets the value of the consumableGoodsIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsumableGoodsIndicator(String value) {
        this.consumableGoodsIndicator = value;
    }

    /**
     * Gets the value of the taxableIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxableIndicator() {
        return taxableIndicator;
    }

    /**
     * Sets the value of the taxableIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxableIndicator(String value) {
        this.taxableIndicator = value;
    }

    /**
     * Gets the value of the deliveryThreshold property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryThreshold() {
        return deliveryThreshold;
    }

    /**
     * Sets the value of the deliveryThreshold property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryThreshold(String value) {
        this.deliveryThreshold = value;
    }

    /**
     * Gets the value of the mpnIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMpnIndicator() {
        return mpnIndicator;
    }

    /**
     * Sets the value of the mpnIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMpnIndicator(String value) {
        this.mpnIndicator = value;
    }

    /**
     * Gets the value of the accessoryIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccessoryIndicator() {
        return accessoryIndicator;
    }

    /**
     * Sets the value of the accessoryIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccessoryIndicator(String value) {
        this.accessoryIndicator = value;
    }

    /**
     * Gets the value of the alternateSubstituteIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlternateSubstituteIndicator() {
        return alternateSubstituteIndicator;
    }

    /**
     * Sets the value of the alternateSubstituteIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlternateSubstituteIndicator(String value) {
        this.alternateSubstituteIndicator = value;
    }

    /**
     * Gets the value of the quoteableFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuoteableFlag() {
        return quoteableFlag;
    }

    /**
     * Sets the value of the quoteableFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuoteableFlag(String value) {
        this.quoteableFlag = value;
    }

    /**
     * Gets the value of the displaySkuFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplaySkuFlag() {
        return displaySkuFlag;
    }

    /**
     * Sets the value of the displaySkuFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplaySkuFlag(String value) {
        this.displaySkuFlag = value;
    }

    /**
     * Gets the value of the misshipFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMisshipFlag() {
        return misshipFlag;
    }

    /**
     * Sets the value of the misshipFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMisshipFlag(String value) {
        this.misshipFlag = value;
    }

    /**
     * Gets the value of the procurementCalculationFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcurementCalculationFlag() {
        return procurementCalculationFlag;
    }

    /**
     * Sets the value of the procurementCalculationFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcurementCalculationFlag(String value) {
        this.procurementCalculationFlag = value;
    }

}
