//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 10:48:26 AM CDT 
//


package com.officedepot;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SkuType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SkuType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Id" type="{http://eai.officedepot.com/model/Inventory}SkuIdType" minOccurs="0"/&gt;
 *         &lt;element name="skuGroup" type="{http://eai.officedepot.com/model/Inventory}SkuGroupType" minOccurs="0"/&gt;
 *         &lt;element name="skuDepartment" type="{http://eai.officedepot.com/model/Inventory}SkuDepartmentType" minOccurs="0"/&gt;
 *         &lt;element name="skuShortDescription" type="{http://eai.officedepot.com/model/Inventory}SkuShortDescriptionType" minOccurs="0"/&gt;
 *         &lt;element name="skuDescription" type="{http://eai.officedepot.com/model/Inventory}SkuDescriptionType" minOccurs="0"/&gt;
 *         &lt;element name="skuSupplier" type="{http://eai.officedepot.com/model/Inventory}SkuSupplierType" minOccurs="0"/&gt;
 *         &lt;element name="skuBrandDetail" type="{http://eai.officedepot.com/model/Inventory}SkuBrandDetailType" minOccurs="0"/&gt;
 *         &lt;element name="skuUPC" type="{http://eai.officedepot.com/model/Inventory}SkuUPCType" minOccurs="0"/&gt;
 *         &lt;element name="skuUom" type="{http://eai.officedepot.com/model/ODCommon}BaseMeasurementType" minOccurs="0"/&gt;
 *         &lt;element name="parentSubClass" type="{http://eai.officedepot.com/model/Inventory}SkuSubClassDetailType" minOccurs="0"/&gt;
 *         &lt;element name="skuListPrice" type="{http://eai.officedepot.com/model/ODCommon}FinanicalAmountType" minOccurs="0"/&gt;
 *         &lt;element name="skuMSRP" type="{http://eai.officedepot.com/model/ODCommon}FinanicalAmountType" minOccurs="0"/&gt;
 *         &lt;element name="minimumShipToStoreQuantityUPC" type="{http://eai.officedepot.com/model/Inventory}SkuUPCType" minOccurs="0"/&gt;
 *         &lt;element name="harmonizedTariffNumber" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="recycledMaterialInformation" type="{http://eai.officedepot.com/model/Inventory}RecycledMaterialInformationType" minOccurs="0"/&gt;
 *         &lt;element name="batteryInformation" type="{http://eai.officedepot.com/model/Inventory}BatteryInformationType" minOccurs="0"/&gt;
 *         &lt;element name="skuAttributes" type="{http://eai.officedepot.com/model/Inventory}SkuAttributesType" minOccurs="0"/&gt;
 *         &lt;element name="skuSupplierRelationship" type="{http://eai.officedepot.com/model/Supplier}SupplierItemRelationshipType" minOccurs="0"/&gt;
 *         &lt;element name="skuDepartmentDetail" type="{http://eai.officedepot.com/model/Inventory}SkuDepartmentDetailType" minOccurs="0"/&gt;
 *         &lt;element name="privateBrandDetail" type="{http://eai.officedepot.com/model/Inventory}SkuBrandDetailType" minOccurs="0"/&gt;
 *         &lt;element name="skuManufacturer" type="{http://eai.officedepot.com/model/Inventory}ItemManufacturerType" minOccurs="0"/&gt;
 *         &lt;element name="systemClassifier" type="{http://eai.officedepot.com/model/ODCommon}SystemClassifierType" minOccurs="0"/&gt;
 *         &lt;element name="skuUnitsPerPackage" type="{http://eai.officedepot.com/model/ODCommon}QuantityType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SkuType", namespace = "http://eai.officedepot.com/model/Inventory", propOrder = {
    "id",
    "skuGroup",
    "skuDepartment",
    "skuShortDescription",
    "skuDescription",
    "skuSupplier",
    "skuBrandDetail",
    "skuUPC",
    "skuUom",
    "parentSubClass",
    "skuListPrice",
    "skuMSRP",
    "minimumShipToStoreQuantityUPC",
    "harmonizedTariffNumber",
    "recycledMaterialInformation",
    "batteryInformation",
    "skuAttributes",
    "skuSupplierRelationship",
    "skuDepartmentDetail",
    "privateBrandDetail",
    "skuManufacturer",
    "systemClassifier",
    "skuUnitsPerPackage"
})
@XmlSeeAlso({
    SkuDetailsType.class
})
public class SkuType {

    @XmlElement(name = "Id")
    protected String id;
    protected String skuGroup;
    protected String skuDepartment;
    protected String skuShortDescription;
    protected String skuDescription;
    protected SkuSupplierType skuSupplier;
    protected SkuBrandDetailType skuBrandDetail;
    protected SkuUPCType skuUPC;
    protected BaseMeasurementType skuUom;
    protected SkuSubClassDetailType parentSubClass;
    protected FinanicalAmountType skuListPrice;
    protected FinanicalAmountType skuMSRP;
    protected SkuUPCType minimumShipToStoreQuantityUPC;
    protected BigInteger harmonizedTariffNumber;
    protected RecycledMaterialInformationType recycledMaterialInformation;
    protected BatteryInformationType batteryInformation;
    protected SkuAttributesType skuAttributes;
    protected SupplierItemRelationshipType skuSupplierRelationship;
    protected SkuDepartmentDetailType skuDepartmentDetail;
    protected SkuBrandDetailType privateBrandDetail;
    protected ItemManufacturerType skuManufacturer;
    protected String systemClassifier;
    protected BigInteger skuUnitsPerPackage;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the skuGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSkuGroup() {
        return skuGroup;
    }

    /**
     * Sets the value of the skuGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSkuGroup(String value) {
        this.skuGroup = value;
    }

    /**
     * Gets the value of the skuDepartment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSkuDepartment() {
        return skuDepartment;
    }

    /**
     * Sets the value of the skuDepartment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSkuDepartment(String value) {
        this.skuDepartment = value;
    }

    /**
     * Gets the value of the skuShortDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSkuShortDescription() {
        return skuShortDescription;
    }

    /**
     * Sets the value of the skuShortDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSkuShortDescription(String value) {
        this.skuShortDescription = value;
    }

    /**
     * Gets the value of the skuDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSkuDescription() {
        return skuDescription;
    }

    /**
     * Sets the value of the skuDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSkuDescription(String value) {
        this.skuDescription = value;
    }

    /**
     * Gets the value of the skuSupplier property.
     * 
     * @return
     *     possible object is
     *     {@link SkuSupplierType }
     *     
     */
    public SkuSupplierType getSkuSupplier() {
        return skuSupplier;
    }

    /**
     * Sets the value of the skuSupplier property.
     * 
     * @param value
     *     allowed object is
     *     {@link SkuSupplierType }
     *     
     */
    public void setSkuSupplier(SkuSupplierType value) {
        this.skuSupplier = value;
    }

    /**
     * Gets the value of the skuBrandDetail property.
     * 
     * @return
     *     possible object is
     *     {@link SkuBrandDetailType }
     *     
     */
    public SkuBrandDetailType getSkuBrandDetail() {
        return skuBrandDetail;
    }

    /**
     * Sets the value of the skuBrandDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link SkuBrandDetailType }
     *     
     */
    public void setSkuBrandDetail(SkuBrandDetailType value) {
        this.skuBrandDetail = value;
    }

    /**
     * Gets the value of the skuUPC property.
     * 
     * @return
     *     possible object is
     *     {@link SkuUPCType }
     *     
     */
    public SkuUPCType getSkuUPC() {
        return skuUPC;
    }

    /**
     * Sets the value of the skuUPC property.
     * 
     * @param value
     *     allowed object is
     *     {@link SkuUPCType }
     *     
     */
    public void setSkuUPC(SkuUPCType value) {
        this.skuUPC = value;
    }

    /**
     * Gets the value of the skuUom property.
     * 
     * @return
     *     possible object is
     *     {@link BaseMeasurementType }
     *     
     */
    public BaseMeasurementType getSkuUom() {
        return skuUom;
    }

    /**
     * Sets the value of the skuUom property.
     * 
     * @param value
     *     allowed object is
     *     {@link BaseMeasurementType }
     *     
     */
    public void setSkuUom(BaseMeasurementType value) {
        this.skuUom = value;
    }

    /**
     * Gets the value of the parentSubClass property.
     * 
     * @return
     *     possible object is
     *     {@link SkuSubClassDetailType }
     *     
     */
    public SkuSubClassDetailType getParentSubClass() {
        return parentSubClass;
    }

    /**
     * Sets the value of the parentSubClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link SkuSubClassDetailType }
     *     
     */
    public void setParentSubClass(SkuSubClassDetailType value) {
        this.parentSubClass = value;
    }

    /**
     * Gets the value of the skuListPrice property.
     * 
     * @return
     *     possible object is
     *     {@link FinanicalAmountType }
     *     
     */
    public FinanicalAmountType getSkuListPrice() {
        return skuListPrice;
    }

    /**
     * Sets the value of the skuListPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link FinanicalAmountType }
     *     
     */
    public void setSkuListPrice(FinanicalAmountType value) {
        this.skuListPrice = value;
    }

    /**
     * Gets the value of the skuMSRP property.
     * 
     * @return
     *     possible object is
     *     {@link FinanicalAmountType }
     *     
     */
    public FinanicalAmountType getSkuMSRP() {
        return skuMSRP;
    }

    /**
     * Sets the value of the skuMSRP property.
     * 
     * @param value
     *     allowed object is
     *     {@link FinanicalAmountType }
     *     
     */
    public void setSkuMSRP(FinanicalAmountType value) {
        this.skuMSRP = value;
    }

    /**
     * Gets the value of the minimumShipToStoreQuantityUPC property.
     * 
     * @return
     *     possible object is
     *     {@link SkuUPCType }
     *     
     */
    public SkuUPCType getMinimumShipToStoreQuantityUPC() {
        return minimumShipToStoreQuantityUPC;
    }

    /**
     * Sets the value of the minimumShipToStoreQuantityUPC property.
     * 
     * @param value
     *     allowed object is
     *     {@link SkuUPCType }
     *     
     */
    public void setMinimumShipToStoreQuantityUPC(SkuUPCType value) {
        this.minimumShipToStoreQuantityUPC = value;
    }

    /**
     * Gets the value of the harmonizedTariffNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHarmonizedTariffNumber() {
        return harmonizedTariffNumber;
    }

    /**
     * Sets the value of the harmonizedTariffNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHarmonizedTariffNumber(BigInteger value) {
        this.harmonizedTariffNumber = value;
    }

    /**
     * Gets the value of the recycledMaterialInformation property.
     * 
     * @return
     *     possible object is
     *     {@link RecycledMaterialInformationType }
     *     
     */
    public RecycledMaterialInformationType getRecycledMaterialInformation() {
        return recycledMaterialInformation;
    }

    /**
     * Sets the value of the recycledMaterialInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecycledMaterialInformationType }
     *     
     */
    public void setRecycledMaterialInformation(RecycledMaterialInformationType value) {
        this.recycledMaterialInformation = value;
    }

    /**
     * Gets the value of the batteryInformation property.
     * 
     * @return
     *     possible object is
     *     {@link BatteryInformationType }
     *     
     */
    public BatteryInformationType getBatteryInformation() {
        return batteryInformation;
    }

    /**
     * Sets the value of the batteryInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link BatteryInformationType }
     *     
     */
    public void setBatteryInformation(BatteryInformationType value) {
        this.batteryInformation = value;
    }

    /**
     * Gets the value of the skuAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link SkuAttributesType }
     *     
     */
    public SkuAttributesType getSkuAttributes() {
        return skuAttributes;
    }

    /**
     * Sets the value of the skuAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link SkuAttributesType }
     *     
     */
    public void setSkuAttributes(SkuAttributesType value) {
        this.skuAttributes = value;
    }

    /**
     * Gets the value of the skuSupplierRelationship property.
     * 
     * @return
     *     possible object is
     *     {@link SupplierItemRelationshipType }
     *     
     */
    public SupplierItemRelationshipType getSkuSupplierRelationship() {
        return skuSupplierRelationship;
    }

    /**
     * Sets the value of the skuSupplierRelationship property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupplierItemRelationshipType }
     *     
     */
    public void setSkuSupplierRelationship(SupplierItemRelationshipType value) {
        this.skuSupplierRelationship = value;
    }

    /**
     * Gets the value of the skuDepartmentDetail property.
     * 
     * @return
     *     possible object is
     *     {@link SkuDepartmentDetailType }
     *     
     */
    public SkuDepartmentDetailType getSkuDepartmentDetail() {
        return skuDepartmentDetail;
    }

    /**
     * Sets the value of the skuDepartmentDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link SkuDepartmentDetailType }
     *     
     */
    public void setSkuDepartmentDetail(SkuDepartmentDetailType value) {
        this.skuDepartmentDetail = value;
    }

    /**
     * Gets the value of the privateBrandDetail property.
     * 
     * @return
     *     possible object is
     *     {@link SkuBrandDetailType }
     *     
     */
    public SkuBrandDetailType getPrivateBrandDetail() {
        return privateBrandDetail;
    }

    /**
     * Sets the value of the privateBrandDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link SkuBrandDetailType }
     *     
     */
    public void setPrivateBrandDetail(SkuBrandDetailType value) {
        this.privateBrandDetail = value;
    }

    /**
     * Gets the value of the skuManufacturer property.
     * 
     * @return
     *     possible object is
     *     {@link ItemManufacturerType }
     *     
     */
    public ItemManufacturerType getSkuManufacturer() {
        return skuManufacturer;
    }

    /**
     * Sets the value of the skuManufacturer property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemManufacturerType }
     *     
     */
    public void setSkuManufacturer(ItemManufacturerType value) {
        this.skuManufacturer = value;
    }

    /**
     * Gets the value of the systemClassifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystemClassifier() {
        return systemClassifier;
    }

    /**
     * Sets the value of the systemClassifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystemClassifier(String value) {
        this.systemClassifier = value;
    }

    /**
     * Gets the value of the skuUnitsPerPackage property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSkuUnitsPerPackage() {
        return skuUnitsPerPackage;
    }

    /**
     * Sets the value of the skuUnitsPerPackage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSkuUnitsPerPackage(BigInteger value) {
        this.skuUnitsPerPackage = value;
    }

}
