//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 10:48:26 AM CDT 
//


package com.officedepot;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SkuUPCInternalLayeringType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SkuUPCInternalLayeringType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="subUPCInLayerQuantity" type="{http://eai.officedepot.com/model/ODCommon}QuantityType" minOccurs="0"/&gt;
 *         &lt;element name="layersStackedInUPC" type="{http://eai.officedepot.com/model/ODCommon}QuantityType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SkuUPCInternalLayeringType", namespace = "http://eai.officedepot.com/model/Inventory", propOrder = {
    "subUPCInLayerQuantity",
    "layersStackedInUPC"
})
public class SkuUPCInternalLayeringType {

    protected BigInteger subUPCInLayerQuantity;
    protected BigInteger layersStackedInUPC;

    /**
     * Gets the value of the subUPCInLayerQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSubUPCInLayerQuantity() {
        return subUPCInLayerQuantity;
    }

    /**
     * Sets the value of the subUPCInLayerQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSubUPCInLayerQuantity(BigInteger value) {
        this.subUPCInLayerQuantity = value;
    }

    /**
     * Gets the value of the layersStackedInUPC property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLayersStackedInUPC() {
        return layersStackedInUPC;
    }

    /**
     * Sets the value of the layersStackedInUPC property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLayersStackedInUPC(BigInteger value) {
        this.layersStackedInUPC = value;
    }

}
