//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 10:48:26 AM CDT 
//


package com.officedepot;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Represents UPC Type definition for SKU
 * 
 * <p>Java class for SkuUPCType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SkuUPCType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="upcCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="upcIndicator" type="{http://eai.officedepot.com/model/Inventory}SkuUPCIndicatorType" minOccurs="0"/&gt;
 *         &lt;element name="upcPackageType" type="{http://eai.officedepot.com/model/Inventory}SkuUPCPackageTypeType" minOccurs="0"/&gt;
 *         &lt;element name="isPrimaryUPC" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="upcProductCodeSubset" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="upcQuantity" type="{http://eai.officedepot.com/model/ODCommon}QuantityType" minOccurs="0"/&gt;
 *         &lt;element name="upcPhysicalAttributes" type="{http://eai.officedepot.com/model/Inventory}SkuUPCPhysicalAttributesType" minOccurs="0"/&gt;
 *         &lt;element name="upcInternalLayering" type="{http://eai.officedepot.com/model/Inventory}SkuUPCInternalLayeringType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SkuUPCType", namespace = "http://eai.officedepot.com/model/Inventory", propOrder = {
    "upcCode",
    "upcIndicator",
    "upcPackageType",
    "isPrimaryUPC",
    "upcProductCodeSubset",
    "upcQuantity",
    "upcPhysicalAttributes",
    "upcInternalLayering"
})
public class SkuUPCType {

    protected String upcCode;
    @XmlSchemaType(name = "string")
    protected SkuUPCIndicatorType upcIndicator;
    @XmlSchemaType(name = "string")
    protected SkuUPCPackageTypeType upcPackageType;
    protected Boolean isPrimaryUPC;
    protected String upcProductCodeSubset;
    protected BigInteger upcQuantity;
    protected SkuUPCPhysicalAttributesType upcPhysicalAttributes;
    protected SkuUPCInternalLayeringType upcInternalLayering;

    /**
     * Gets the value of the upcCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpcCode() {
        return upcCode;
    }

    /**
     * Sets the value of the upcCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpcCode(String value) {
        this.upcCode = value;
    }

    /**
     * Gets the value of the upcIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link SkuUPCIndicatorType }
     *     
     */
    public SkuUPCIndicatorType getUpcIndicator() {
        return upcIndicator;
    }

    /**
     * Sets the value of the upcIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link SkuUPCIndicatorType }
     *     
     */
    public void setUpcIndicator(SkuUPCIndicatorType value) {
        this.upcIndicator = value;
    }

    /**
     * Gets the value of the upcPackageType property.
     * 
     * @return
     *     possible object is
     *     {@link SkuUPCPackageTypeType }
     *     
     */
    public SkuUPCPackageTypeType getUpcPackageType() {
        return upcPackageType;
    }

    /**
     * Sets the value of the upcPackageType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SkuUPCPackageTypeType }
     *     
     */
    public void setUpcPackageType(SkuUPCPackageTypeType value) {
        this.upcPackageType = value;
    }

    /**
     * Gets the value of the isPrimaryUPC property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsPrimaryUPC() {
        return isPrimaryUPC;
    }

    /**
     * Sets the value of the isPrimaryUPC property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsPrimaryUPC(Boolean value) {
        this.isPrimaryUPC = value;
    }

    /**
     * Gets the value of the upcProductCodeSubset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpcProductCodeSubset() {
        return upcProductCodeSubset;
    }

    /**
     * Sets the value of the upcProductCodeSubset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpcProductCodeSubset(String value) {
        this.upcProductCodeSubset = value;
    }

    /**
     * Gets the value of the upcQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUpcQuantity() {
        return upcQuantity;
    }

    /**
     * Sets the value of the upcQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUpcQuantity(BigInteger value) {
        this.upcQuantity = value;
    }

    /**
     * Gets the value of the upcPhysicalAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link SkuUPCPhysicalAttributesType }
     *     
     */
    public SkuUPCPhysicalAttributesType getUpcPhysicalAttributes() {
        return upcPhysicalAttributes;
    }

    /**
     * Sets the value of the upcPhysicalAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link SkuUPCPhysicalAttributesType }
     *     
     */
    public void setUpcPhysicalAttributes(SkuUPCPhysicalAttributesType value) {
        this.upcPhysicalAttributes = value;
    }

    /**
     * Gets the value of the upcInternalLayering property.
     * 
     * @return
     *     possible object is
     *     {@link SkuUPCInternalLayeringType }
     *     
     */
    public SkuUPCInternalLayeringType getUpcInternalLayering() {
        return upcInternalLayering;
    }

    /**
     * Sets the value of the upcInternalLayering property.
     * 
     * @param value
     *     allowed object is
     *     {@link SkuUPCInternalLayeringType }
     *     
     */
    public void setUpcInternalLayering(SkuUPCInternalLayeringType value) {
        this.upcInternalLayering = value;
    }

}
