//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 10:48:26 AM CDT 
//


package com.officedepot;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SkuUPCPhysicalAttributesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SkuUPCPhysicalAttributesType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="upcGrossWeight" type="{http://eai.officedepot.com/model/ODCommon}BaseMeasurementType" minOccurs="0"/&gt;
 *         &lt;element name="upcNetWeight" type="{http://eai.officedepot.com/model/ODCommon}BaseMeasurementType" minOccurs="0"/&gt;
 *         &lt;element name="upcDimension" type="{http://eai.officedepot.com/model/ODCommon}DimensionType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SkuUPCPhysicalAttributesType", namespace = "http://eai.officedepot.com/model/Inventory", propOrder = {
    "upcGrossWeight",
    "upcNetWeight",
    "upcDimension"
})
public class SkuUPCPhysicalAttributesType {

    protected BaseMeasurementType upcGrossWeight;
    protected BaseMeasurementType upcNetWeight;
    protected DimensionType upcDimension;

    /**
     * Gets the value of the upcGrossWeight property.
     * 
     * @return
     *     possible object is
     *     {@link BaseMeasurementType }
     *     
     */
    public BaseMeasurementType getUpcGrossWeight() {
        return upcGrossWeight;
    }

    /**
     * Sets the value of the upcGrossWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BaseMeasurementType }
     *     
     */
    public void setUpcGrossWeight(BaseMeasurementType value) {
        this.upcGrossWeight = value;
    }

    /**
     * Gets the value of the upcNetWeight property.
     * 
     * @return
     *     possible object is
     *     {@link BaseMeasurementType }
     *     
     */
    public BaseMeasurementType getUpcNetWeight() {
        return upcNetWeight;
    }

    /**
     * Sets the value of the upcNetWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BaseMeasurementType }
     *     
     */
    public void setUpcNetWeight(BaseMeasurementType value) {
        this.upcNetWeight = value;
    }

    /**
     * Gets the value of the upcDimension property.
     * 
     * @return
     *     possible object is
     *     {@link DimensionType }
     *     
     */
    public DimensionType getUpcDimension() {
        return upcDimension;
    }

    /**
     * Sets the value of the upcDimension property.
     * 
     * @param value
     *     allowed object is
     *     {@link DimensionType }
     *     
     */
    public void setUpcDimension(DimensionType value) {
        this.upcDimension = value;
    }

}
