//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 10:48:26 AM CDT 
//


package com.officedepot;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * ODP - OfficeDepot South supplierItemUPCSet
 * OMX - OfficeDepot North supplierItemUPCSet
 * 
 * <p>Java class for SupplierItemUPCSetType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SupplierItemUPCSetType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="packageLevelUPCList" type="{http://eai.officedepot.com/model/Inventory}SkuPackageLevelUPCListType" minOccurs="0"/&gt;
 *         &lt;element name="sellUnitUPCList" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="sellUnitUPC" type="{http://eai.officedepot.com/model/Inventory}SkuUPCType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="systemClassifier" type="{http://eai.officedepot.com/model/ODCommon}SystemClassifierType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SupplierItemUPCSetType", namespace = "http://eai.officedepot.com/model/Supplier", propOrder = {
    "packageLevelUPCList",
    "sellUnitUPCList",
    "systemClassifier"
})
public class SupplierItemUPCSetType {

    protected SkuPackageLevelUPCListType packageLevelUPCList;
    protected SupplierItemUPCSetType.SellUnitUPCList sellUnitUPCList;
    protected String systemClassifier;

    /**
     * Gets the value of the packageLevelUPCList property.
     * 
     * @return
     *     possible object is
     *     {@link SkuPackageLevelUPCListType }
     *     
     */
    public SkuPackageLevelUPCListType getPackageLevelUPCList() {
        return packageLevelUPCList;
    }

    /**
     * Sets the value of the packageLevelUPCList property.
     * 
     * @param value
     *     allowed object is
     *     {@link SkuPackageLevelUPCListType }
     *     
     */
    public void setPackageLevelUPCList(SkuPackageLevelUPCListType value) {
        this.packageLevelUPCList = value;
    }

    /**
     * Gets the value of the sellUnitUPCList property.
     * 
     * @return
     *     possible object is
     *     {@link SupplierItemUPCSetType.SellUnitUPCList }
     *     
     */
    public SupplierItemUPCSetType.SellUnitUPCList getSellUnitUPCList() {
        return sellUnitUPCList;
    }

    /**
     * Sets the value of the sellUnitUPCList property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupplierItemUPCSetType.SellUnitUPCList }
     *     
     */
    public void setSellUnitUPCList(SupplierItemUPCSetType.SellUnitUPCList value) {
        this.sellUnitUPCList = value;
    }

    /**
     * Gets the value of the systemClassifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystemClassifier() {
        return systemClassifier;
    }

    /**
     * Sets the value of the systemClassifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystemClassifier(String value) {
        this.systemClassifier = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="sellUnitUPC" type="{http://eai.officedepot.com/model/Inventory}SkuUPCType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "sellUnitUPC"
    })
    public static class SellUnitUPCList {

        @XmlElement(namespace = "http://eai.officedepot.com/model/Supplier")
        protected List<SkuUPCType> sellUnitUPC;

        /**
         * Gets the value of the sellUnitUPC property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the sellUnitUPC property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSellUnitUPC().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SkuUPCType }
         * 
         * 
         */
        public List<SkuUPCType> getSellUnitUPC() {
            if (sellUnitUPC == null) {
                sellUnitUPC = new ArrayList<SkuUPCType>();
            }
            return this.sellUnitUPC;
        }

    }

}
