//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 10:48:26 AM CDT 
//


package com.officedepot;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Identifies attributes belonging to supplier. Supplier
 * 				has a relationship to supplier sites.
 * 			
 * 
 * <p>Java class for SupplierType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SupplierType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="supplierId" type="{http://eai.officedepot.com/model/Supplier}SupplierIDType" minOccurs="0"/&gt;
 *         &lt;element name="supplierReferenceNumber" type="{http://eai.officedepot.com/model/ODCommon}KeyValuePairsType" minOccurs="0"/&gt;
 *         &lt;element name="supplierCompanyIdentity" type="{http://eai.officedepot.com/model/ODCommon}CompanyIdentityType" minOccurs="0"/&gt;
 *         &lt;element name="supplierContacts" type="{http://eai.officedepot.com/model/Supplier}SupplierContactAssociationType" minOccurs="0"/&gt;
 *         &lt;element name="supplierSites" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="supplierSite" type="{http://eai.officedepot.com/model/Supplier}SiteType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="businessClassification" type="{http://eai.officedepot.com/model/Supplier}BusinessClassificationType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SupplierType", namespace = "http://eai.officedepot.com/model/Supplier", propOrder = {
    "supplierId",
    "supplierReferenceNumber",
    "supplierCompanyIdentity",
    "supplierContacts",
    "supplierSites",
    "businessClassification"
})
public class SupplierType {

    protected String supplierId;
    protected KeyValuePairsType supplierReferenceNumber;
    protected CompanyIdentityType supplierCompanyIdentity;
    protected SupplierContactAssociationType supplierContacts;
    protected List<SupplierType.SupplierSites> supplierSites;
    protected BusinessClassificationType businessClassification;

    /**
     * Gets the value of the supplierId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplierId() {
        return supplierId;
    }

    /**
     * Sets the value of the supplierId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplierId(String value) {
        this.supplierId = value;
    }

    /**
     * Gets the value of the supplierReferenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link KeyValuePairsType }
     *     
     */
    public KeyValuePairsType getSupplierReferenceNumber() {
        return supplierReferenceNumber;
    }

    /**
     * Sets the value of the supplierReferenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeyValuePairsType }
     *     
     */
    public void setSupplierReferenceNumber(KeyValuePairsType value) {
        this.supplierReferenceNumber = value;
    }

    /**
     * Gets the value of the supplierCompanyIdentity property.
     * 
     * @return
     *     possible object is
     *     {@link CompanyIdentityType }
     *     
     */
    public CompanyIdentityType getSupplierCompanyIdentity() {
        return supplierCompanyIdentity;
    }

    /**
     * Sets the value of the supplierCompanyIdentity property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompanyIdentityType }
     *     
     */
    public void setSupplierCompanyIdentity(CompanyIdentityType value) {
        this.supplierCompanyIdentity = value;
    }

    /**
     * Gets the value of the supplierContacts property.
     * 
     * @return
     *     possible object is
     *     {@link SupplierContactAssociationType }
     *     
     */
    public SupplierContactAssociationType getSupplierContacts() {
        return supplierContacts;
    }

    /**
     * Sets the value of the supplierContacts property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupplierContactAssociationType }
     *     
     */
    public void setSupplierContacts(SupplierContactAssociationType value) {
        this.supplierContacts = value;
    }

    /**
     * Gets the value of the supplierSites property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the supplierSites property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSupplierSites().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SupplierType.SupplierSites }
     * 
     * 
     */
    public List<SupplierType.SupplierSites> getSupplierSites() {
        if (supplierSites == null) {
            supplierSites = new ArrayList<SupplierType.SupplierSites>();
        }
        return this.supplierSites;
    }

    /**
     * Gets the value of the businessClassification property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessClassificationType }
     *     
     */
    public BusinessClassificationType getBusinessClassification() {
        return businessClassification;
    }

    /**
     * Sets the value of the businessClassification property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessClassificationType }
     *     
     */
    public void setBusinessClassification(BusinessClassificationType value) {
        this.businessClassification = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="supplierSite" type="{http://eai.officedepot.com/model/Supplier}SiteType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "supplierSite"
    })
    public static class SupplierSites {

        @XmlElement(namespace = "http://eai.officedepot.com/model/Supplier")
        protected List<SiteType> supplierSite;

        /**
         * Gets the value of the supplierSite property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the supplierSite property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSupplierSite().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SiteType }
         * 
         * 
         */
        public List<SiteType> getSupplierSite() {
            if (supplierSite == null) {
                supplierSite = new ArrayList<SiteType>();
            }
            return this.supplierSite;
        }

    }

}
