//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 10:48:26 AM CDT 
//


package com.officedepot;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Contact identity information related to suppliers
 * 			
 * 
 * <p>Java class for SupplierContactType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SupplierContactType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://eai.officedepot.com/model/ODCommon}PersonType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="supplierContactType" type="{http://eai.officedepot.com/model/Supplier}SupplierContactTypeType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SupplierContactType", namespace = "http://eai.officedepot.com/model/Supplier", propOrder = {
    "supplierContactType"
})
public class SupplierContactType
    extends PersonType
{

    @XmlSchemaType(name = "string")
    protected SupplierContactTypeType supplierContactType;

    /**
     * Gets the value of the supplierContactType property.
     * 
     * @return
     *     possible object is
     *     {@link SupplierContactTypeType }
     *     
     */
    public SupplierContactTypeType getSupplierContactType() {
        return supplierContactType;
    }

    /**
     * Sets the value of the supplierContactType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupplierContactTypeType }
     *     
     */
    public void setSupplierContactType(SupplierContactTypeType value) {
        this.supplierContactType = value;
    }

}
