//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 10:48:26 AM CDT 
//


package com.officedepot;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * 
 * 				Identifies attributes belonging to supplier site
 * 			
 * 
 * <p>Java class for SupplierRelationshipType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SupplierRelationshipType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="isPrimaryPaySite" type="{http://eai.officedepot.com/model/Supplier}IsPrimaryPaySiteType" minOccurs="0"/&gt;
 *         &lt;element name="isRFQSite" type="{http://eai.officedepot.com/model/Supplier}IsRFQSiteType" minOccurs="0"/&gt;
 *         &lt;element name="isARAttention" type="{http://eai.officedepot.com/model/Supplier}IsARAttentionType" minOccurs="0"/&gt;
 *         &lt;element name="currencyCode" type="{http://eai.officedepot.com/model/ODCommon}CurrencyCodeType" minOccurs="0"/&gt;
 *         &lt;element name="languageCode" type="{http://eai.officedepot.com/model/ODCommon}LanguageCodeType" minOccurs="0"/&gt;
 *         &lt;element name="inventoryTypeCode" type="{http://eai.officedepot.com/model/Supplier}InventoryTypeCodeType" minOccurs="0"/&gt;
 *         &lt;element name="paymentTerm" type="{http://eai.officedepot.com/model/ODCommon}PaymentTermType" minOccurs="0"/&gt;
 *         &lt;element name="freightTermCode" type="{http://eai.officedepot.com/model/Supplier}FreightTermCodeType" minOccurs="0"/&gt;
 *         &lt;element name="handlingCode" type="{http://eai.officedepot.com/model/Supplier}HandlingCodeType" minOccurs="0"/&gt;
 *         &lt;element name="isDebitMemoAllowed" type="{http://eai.officedepot.com/model/Supplier}IsDebitMemoAllowedType" minOccurs="0"/&gt;
 *         &lt;element name="categoryCode" type="{http://eai.officedepot.com/model/Supplier}CategoryCodeType" minOccurs="0"/&gt;
 *         &lt;element name="leadTimeDuration" type="{http://eai.officedepot.com/model/Supplier}LeadTimeDurationType" minOccurs="0"/&gt;
 *         &lt;element name="isBackOrdered" type="{http://eai.officedepot.com/model/Supplier}IsBackOrderedType" minOccurs="0"/&gt;
 *         &lt;element name="deliveryPolicyCode" type="{http://eai.officedepot.com/model/Supplier}DeliveryPolicyCodeType" minOccurs="0"/&gt;
 *         &lt;element name="prePaidMinimumCode" type="{http://eai.officedepot.com/model/Supplier}PrePaidMinimumCodeType" minOccurs="0"/&gt;
 *         &lt;element name="vendorMinimumAmount" type="{http://eai.officedepot.com/model/Supplier}VendorMinimumAmountType" minOccurs="0"/&gt;
 *         &lt;element name="isVerticalMarket" type="{http://eai.officedepot.com/model/Supplier}IsVerticalMarketType" minOccurs="0"/&gt;
 *         &lt;element name="isAutoReceiptAllowed" type="{http://eai.officedepot.com/model/Supplier}IsAutoReceiptAllowedType" minOccurs="0"/&gt;
 *         &lt;element name="etfSettleDuration" type="{http://eai.officedepot.com/model/Supplier}ETFSettleDurationType" minOccurs="0"/&gt;
 *         &lt;element name="minorityBusinessCode" type="{http://eai.officedepot.com/model/Supplier}MinorityBusinessCodeType" minOccurs="0"/&gt;
 *         &lt;element name="minorityBusinessCategoryCode" type="{http://eai.officedepot.com/model/Supplier}MinorityBusinessCategoryCodeType" minOccurs="0"/&gt;
 *         &lt;element name="isPickPack" type="{http://eai.officedepot.com/model/Supplier}IsPickPackType" minOccurs="0"/&gt;
 *         &lt;element name="isCombinePickTicket" type="{http://eai.officedepot.com/model/Supplier}IsCombinePickTicketType" minOccurs="0"/&gt;
 *         &lt;element name="officeDepotSignedDateTime" type="{http://eai.officedepot.com/model/Supplier}OfficeDepotSignedDateTimeType" minOccurs="0"/&gt;
 *         &lt;element name="vendorSignedDateTime" type="{http://eai.officedepot.com/model/Supplier}VendorSignedDateTimeType" minOccurs="0"/&gt;
 *         &lt;element name="isDeductFromInvoice" type="{http://eai.officedepot.com/model/Supplier}IsDeductFromInvoiceType" minOccurs="0"/&gt;
 *         &lt;element name="isNewStore" type="{http://eai.officedepot.com/model/Supplier}IsNewStoreType" minOccurs="0"/&gt;
 *         &lt;element name="newStoreTerms" type="{http://eai.officedepot.com/model/Supplier}NewStoreTermsType" minOccurs="0"/&gt;
 *         &lt;element name="isSeasonal" type="{http://eai.officedepot.com/model/Supplier}IsSeasonalType" minOccurs="0"/&gt;
 *         &lt;element name="seasonalTerms" type="{http://eai.officedepot.com/model/Supplier}SeasonalTermsType" minOccurs="0"/&gt;
 *         &lt;element name="isLateShip" type="{http://eai.officedepot.com/model/Supplier}IsLateShipType" minOccurs="0"/&gt;
 *         &lt;element name="isPermanentRGA" type="{http://eai.officedepot.com/model/Supplier}IsPermanentRGAType" minOccurs="0"/&gt;
 *         &lt;element name="isRGAMark" type="{http://eai.officedepot.com/model/Supplier}IsRGAMarkType" minOccurs="0"/&gt;
 *         &lt;element name="destroyAllowAmount" type="{http://eai.officedepot.com/model/Supplier}DestroyAllowAmountType" minOccurs="0"/&gt;
 *         &lt;element name="damageDestroyLimitAmount" type="{http://eai.officedepot.com/model/Supplier}DamageDestroyLimitAmountType" minOccurs="0"/&gt;
 *         &lt;element name="isRemovePriceSticker" type="{http://eai.officedepot.com/model/Supplier}IsRemovePriceStickerType" minOccurs="0"/&gt;
 *         &lt;element name="isContactForRGA" type="{http://eai.officedepot.com/model/Supplier}IsContactForRGAType" minOccurs="0"/&gt;
 *         &lt;element name="isDestroy" type="{http://eai.officedepot.com/model/Supplier}IsDestroyType" minOccurs="0"/&gt;
 *         &lt;element name="isSerialControl" type="{http://eai.officedepot.com/model/Supplier}IsSerialControlType" minOccurs="0"/&gt;
 *         &lt;element name="isObsoleteItem" type="{http://eai.officedepot.com/model/Supplier}IsObsoleteItemType" minOccurs="0"/&gt;
 *         &lt;element name="obsoleteAllowancePercent" type="{http://eai.officedepot.com/model/Supplier}ObsoleteAllowancePercentType" minOccurs="0"/&gt;
 *         &lt;element name="obsoleteAllowanceDuration" type="{http://eai.officedepot.com/model/Supplier}ObsoleteAllowanceDurationType" minOccurs="0"/&gt;
 *         &lt;element name="rtv" type="{http://eai.officedepot.com/model/Supplier}RTVType" minOccurs="0"/&gt;
 *         &lt;element name="usesEDI810" type="{http://eai.officedepot.com/model/Supplier}UsesEDIType" minOccurs="0"/&gt;
 *         &lt;element name="usesEDI820" type="{http://eai.officedepot.com/model/Supplier}UsesEDIType" minOccurs="0"/&gt;
 *         &lt;element name="usesEDI832" type="{http://eai.officedepot.com/model/Supplier}UsesEDIType" minOccurs="0"/&gt;
 *         &lt;element name="usesEDI846" type="{http://eai.officedepot.com/model/Supplier}UsesEDIType" minOccurs="0"/&gt;
 *         &lt;element name="usesEDI850" type="{http://eai.officedepot.com/model/Supplier}UsesEDIType" minOccurs="0"/&gt;
 *         &lt;element name="usesEDI852" type="{http://eai.officedepot.com/model/Supplier}UsesEDIType" minOccurs="0"/&gt;
 *         &lt;element name="usesEDI855" type="{http://eai.officedepot.com/model/Supplier}UsesEDIType" minOccurs="0"/&gt;
 *         &lt;element name="usesEDI860" type="{http://eai.officedepot.com/model/Supplier}UsesEDIType" minOccurs="0"/&gt;
 *         &lt;element name="usesEDI861" type="{http://eai.officedepot.com/model/Supplier}UsesEDIType" minOccurs="0"/&gt;
 *         &lt;element name="ediDistributionCode" type="{http://eai.officedepot.com/model/Supplier}EDIDistributionCodeType" minOccurs="0"/&gt;
 *         &lt;element name="shipFromPortId" type="{http://eai.officedepot.com/model/ODCommon}IDType" minOccurs="0"/&gt;
 *         &lt;element name="manufacturingSiteId" type="{http://eai.officedepot.com/model/ODCommon}IDType" minOccurs="0"/&gt;
 *         &lt;element name="buyingAgentSiteId" type="{http://eai.officedepot.com/model/ODCommon}IDType" minOccurs="0"/&gt;
 *         &lt;element name="freightForwarderSiteId" type="{http://eai.officedepot.com/model/ODCommon}IDType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SupplierRelationshipType", namespace = "http://eai.officedepot.com/model/Supplier", propOrder = {
    "isPrimaryPaySite",
    "isRFQSite",
    "isARAttention",
    "currencyCode",
    "languageCode",
    "inventoryTypeCode",
    "paymentTerm",
    "freightTermCode",
    "handlingCode",
    "isDebitMemoAllowed",
    "categoryCode",
    "leadTimeDuration",
    "isBackOrdered",
    "deliveryPolicyCode",
    "prePaidMinimumCode",
    "vendorMinimumAmount",
    "isVerticalMarket",
    "isAutoReceiptAllowed",
    "etfSettleDuration",
    "minorityBusinessCode",
    "minorityBusinessCategoryCode",
    "isPickPack",
    "isCombinePickTicket",
    "officeDepotSignedDateTime",
    "vendorSignedDateTime",
    "isDeductFromInvoice",
    "isNewStore",
    "newStoreTerms",
    "isSeasonal",
    "seasonalTerms",
    "isLateShip",
    "isPermanentRGA",
    "isRGAMark",
    "destroyAllowAmount",
    "damageDestroyLimitAmount",
    "isRemovePriceSticker",
    "isContactForRGA",
    "isDestroy",
    "isSerialControl",
    "isObsoleteItem",
    "obsoleteAllowancePercent",
    "obsoleteAllowanceDuration",
    "rtv",
    "usesEDI810",
    "usesEDI820",
    "usesEDI832",
    "usesEDI846",
    "usesEDI850",
    "usesEDI852",
    "usesEDI855",
    "usesEDI860",
    "usesEDI861",
    "ediDistributionCode",
    "shipFromPortId",
    "manufacturingSiteId",
    "buyingAgentSiteId",
    "freightForwarderSiteId"
})
public class SupplierRelationshipType {

    protected Boolean isPrimaryPaySite;
    protected Boolean isRFQSite;
    protected Boolean isARAttention;
    protected String currencyCode;
    protected String languageCode;
    protected String inventoryTypeCode;
    protected PaymentTermType paymentTerm;
    protected String freightTermCode;
    protected String handlingCode;
    protected Boolean isDebitMemoAllowed;
    protected String categoryCode;
    protected String leadTimeDuration;
    protected Boolean isBackOrdered;
    protected String deliveryPolicyCode;
    protected String prePaidMinimumCode;
    protected Double vendorMinimumAmount;
    protected Boolean isVerticalMarket;
    protected Boolean isAutoReceiptAllowed;
    protected String etfSettleDuration;
    protected String minorityBusinessCode;
    protected String minorityBusinessCategoryCode;
    protected Boolean isPickPack;
    protected Boolean isCombinePickTicket;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar officeDepotSignedDateTime;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar vendorSignedDateTime;
    protected Boolean isDeductFromInvoice;
    protected Boolean isNewStore;
    protected String newStoreTerms;
    protected Boolean isSeasonal;
    protected String seasonalTerms;
    protected Boolean isLateShip;
    protected Boolean isPermanentRGA;
    protected Boolean isRGAMark;
    protected Double destroyAllowAmount;
    protected Double damageDestroyLimitAmount;
    protected Boolean isRemovePriceSticker;
    protected Boolean isContactForRGA;
    protected Boolean isDestroy;
    protected Boolean isSerialControl;
    protected Boolean isObsoleteItem;
    protected Double obsoleteAllowancePercent;
    protected String obsoleteAllowanceDuration;
    protected RTVType rtv;
    protected Boolean usesEDI810;
    protected Boolean usesEDI820;
    protected Boolean usesEDI832;
    protected Boolean usesEDI846;
    protected Boolean usesEDI850;
    protected Boolean usesEDI852;
    protected Boolean usesEDI855;
    protected Boolean usesEDI860;
    protected Boolean usesEDI861;
    protected String ediDistributionCode;
    protected String shipFromPortId;
    protected String manufacturingSiteId;
    protected String buyingAgentSiteId;
    protected String freightForwarderSiteId;

    /**
     * Gets the value of the isPrimaryPaySite property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsPrimaryPaySite() {
        return isPrimaryPaySite;
    }

    /**
     * Sets the value of the isPrimaryPaySite property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsPrimaryPaySite(Boolean value) {
        this.isPrimaryPaySite = value;
    }

    /**
     * Gets the value of the isRFQSite property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsRFQSite() {
        return isRFQSite;
    }

    /**
     * Sets the value of the isRFQSite property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsRFQSite(Boolean value) {
        this.isRFQSite = value;
    }

    /**
     * Gets the value of the isARAttention property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsARAttention() {
        return isARAttention;
    }

    /**
     * Sets the value of the isARAttention property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsARAttention(Boolean value) {
        this.isARAttention = value;
    }

    /**
     * Gets the value of the currencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrencyCode() {
        return currencyCode;
    }

    /**
     * Sets the value of the currencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrencyCode(String value) {
        this.currencyCode = value;
    }

    /**
     * Gets the value of the languageCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguageCode() {
        return languageCode;
    }

    /**
     * Sets the value of the languageCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguageCode(String value) {
        this.languageCode = value;
    }

    /**
     * Gets the value of the inventoryTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInventoryTypeCode() {
        return inventoryTypeCode;
    }

    /**
     * Sets the value of the inventoryTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInventoryTypeCode(String value) {
        this.inventoryTypeCode = value;
    }

    /**
     * Gets the value of the paymentTerm property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentTermType }
     *     
     */
    public PaymentTermType getPaymentTerm() {
        return paymentTerm;
    }

    /**
     * Sets the value of the paymentTerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentTermType }
     *     
     */
    public void setPaymentTerm(PaymentTermType value) {
        this.paymentTerm = value;
    }

    /**
     * Gets the value of the freightTermCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreightTermCode() {
        return freightTermCode;
    }

    /**
     * Sets the value of the freightTermCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreightTermCode(String value) {
        this.freightTermCode = value;
    }

    /**
     * Gets the value of the handlingCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHandlingCode() {
        return handlingCode;
    }

    /**
     * Sets the value of the handlingCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHandlingCode(String value) {
        this.handlingCode = value;
    }

    /**
     * Gets the value of the isDebitMemoAllowed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsDebitMemoAllowed() {
        return isDebitMemoAllowed;
    }

    /**
     * Sets the value of the isDebitMemoAllowed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsDebitMemoAllowed(Boolean value) {
        this.isDebitMemoAllowed = value;
    }

    /**
     * Gets the value of the categoryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoryCode() {
        return categoryCode;
    }

    /**
     * Sets the value of the categoryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoryCode(String value) {
        this.categoryCode = value;
    }

    /**
     * Gets the value of the leadTimeDuration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLeadTimeDuration() {
        return leadTimeDuration;
    }

    /**
     * Sets the value of the leadTimeDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLeadTimeDuration(String value) {
        this.leadTimeDuration = value;
    }

    /**
     * Gets the value of the isBackOrdered property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsBackOrdered() {
        return isBackOrdered;
    }

    /**
     * Sets the value of the isBackOrdered property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsBackOrdered(Boolean value) {
        this.isBackOrdered = value;
    }

    /**
     * Gets the value of the deliveryPolicyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryPolicyCode() {
        return deliveryPolicyCode;
    }

    /**
     * Sets the value of the deliveryPolicyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryPolicyCode(String value) {
        this.deliveryPolicyCode = value;
    }

    /**
     * Gets the value of the prePaidMinimumCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrePaidMinimumCode() {
        return prePaidMinimumCode;
    }

    /**
     * Sets the value of the prePaidMinimumCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrePaidMinimumCode(String value) {
        this.prePaidMinimumCode = value;
    }

    /**
     * Gets the value of the vendorMinimumAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getVendorMinimumAmount() {
        return vendorMinimumAmount;
    }

    /**
     * Sets the value of the vendorMinimumAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setVendorMinimumAmount(Double value) {
        this.vendorMinimumAmount = value;
    }

    /**
     * Gets the value of the isVerticalMarket property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsVerticalMarket() {
        return isVerticalMarket;
    }

    /**
     * Sets the value of the isVerticalMarket property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsVerticalMarket(Boolean value) {
        this.isVerticalMarket = value;
    }

    /**
     * Gets the value of the isAutoReceiptAllowed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsAutoReceiptAllowed() {
        return isAutoReceiptAllowed;
    }

    /**
     * Sets the value of the isAutoReceiptAllowed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsAutoReceiptAllowed(Boolean value) {
        this.isAutoReceiptAllowed = value;
    }

    /**
     * Gets the value of the etfSettleDuration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEtfSettleDuration() {
        return etfSettleDuration;
    }

    /**
     * Sets the value of the etfSettleDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEtfSettleDuration(String value) {
        this.etfSettleDuration = value;
    }

    /**
     * Gets the value of the minorityBusinessCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinorityBusinessCode() {
        return minorityBusinessCode;
    }

    /**
     * Sets the value of the minorityBusinessCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinorityBusinessCode(String value) {
        this.minorityBusinessCode = value;
    }

    /**
     * Gets the value of the minorityBusinessCategoryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinorityBusinessCategoryCode() {
        return minorityBusinessCategoryCode;
    }

    /**
     * Sets the value of the minorityBusinessCategoryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinorityBusinessCategoryCode(String value) {
        this.minorityBusinessCategoryCode = value;
    }

    /**
     * Gets the value of the isPickPack property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsPickPack() {
        return isPickPack;
    }

    /**
     * Sets the value of the isPickPack property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsPickPack(Boolean value) {
        this.isPickPack = value;
    }

    /**
     * Gets the value of the isCombinePickTicket property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsCombinePickTicket() {
        return isCombinePickTicket;
    }

    /**
     * Sets the value of the isCombinePickTicket property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsCombinePickTicket(Boolean value) {
        this.isCombinePickTicket = value;
    }

    /**
     * Gets the value of the officeDepotSignedDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOfficeDepotSignedDateTime() {
        return officeDepotSignedDateTime;
    }

    /**
     * Sets the value of the officeDepotSignedDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOfficeDepotSignedDateTime(XMLGregorianCalendar value) {
        this.officeDepotSignedDateTime = value;
    }

    /**
     * Gets the value of the vendorSignedDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getVendorSignedDateTime() {
        return vendorSignedDateTime;
    }

    /**
     * Sets the value of the vendorSignedDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setVendorSignedDateTime(XMLGregorianCalendar value) {
        this.vendorSignedDateTime = value;
    }

    /**
     * Gets the value of the isDeductFromInvoice property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsDeductFromInvoice() {
        return isDeductFromInvoice;
    }

    /**
     * Sets the value of the isDeductFromInvoice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsDeductFromInvoice(Boolean value) {
        this.isDeductFromInvoice = value;
    }

    /**
     * Gets the value of the isNewStore property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsNewStore() {
        return isNewStore;
    }

    /**
     * Sets the value of the isNewStore property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsNewStore(Boolean value) {
        this.isNewStore = value;
    }

    /**
     * Gets the value of the newStoreTerms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewStoreTerms() {
        return newStoreTerms;
    }

    /**
     * Sets the value of the newStoreTerms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewStoreTerms(String value) {
        this.newStoreTerms = value;
    }

    /**
     * Gets the value of the isSeasonal property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsSeasonal() {
        return isSeasonal;
    }

    /**
     * Sets the value of the isSeasonal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsSeasonal(Boolean value) {
        this.isSeasonal = value;
    }

    /**
     * Gets the value of the seasonalTerms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeasonalTerms() {
        return seasonalTerms;
    }

    /**
     * Sets the value of the seasonalTerms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeasonalTerms(String value) {
        this.seasonalTerms = value;
    }

    /**
     * Gets the value of the isLateShip property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsLateShip() {
        return isLateShip;
    }

    /**
     * Sets the value of the isLateShip property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsLateShip(Boolean value) {
        this.isLateShip = value;
    }

    /**
     * Gets the value of the isPermanentRGA property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsPermanentRGA() {
        return isPermanentRGA;
    }

    /**
     * Sets the value of the isPermanentRGA property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsPermanentRGA(Boolean value) {
        this.isPermanentRGA = value;
    }

    /**
     * Gets the value of the isRGAMark property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsRGAMark() {
        return isRGAMark;
    }

    /**
     * Sets the value of the isRGAMark property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsRGAMark(Boolean value) {
        this.isRGAMark = value;
    }

    /**
     * Gets the value of the destroyAllowAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getDestroyAllowAmount() {
        return destroyAllowAmount;
    }

    /**
     * Sets the value of the destroyAllowAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDestroyAllowAmount(Double value) {
        this.destroyAllowAmount = value;
    }

    /**
     * Gets the value of the damageDestroyLimitAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getDamageDestroyLimitAmount() {
        return damageDestroyLimitAmount;
    }

    /**
     * Sets the value of the damageDestroyLimitAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDamageDestroyLimitAmount(Double value) {
        this.damageDestroyLimitAmount = value;
    }

    /**
     * Gets the value of the isRemovePriceSticker property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsRemovePriceSticker() {
        return isRemovePriceSticker;
    }

    /**
     * Sets the value of the isRemovePriceSticker property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsRemovePriceSticker(Boolean value) {
        this.isRemovePriceSticker = value;
    }

    /**
     * Gets the value of the isContactForRGA property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsContactForRGA() {
        return isContactForRGA;
    }

    /**
     * Sets the value of the isContactForRGA property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsContactForRGA(Boolean value) {
        this.isContactForRGA = value;
    }

    /**
     * Gets the value of the isDestroy property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsDestroy() {
        return isDestroy;
    }

    /**
     * Sets the value of the isDestroy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsDestroy(Boolean value) {
        this.isDestroy = value;
    }

    /**
     * Gets the value of the isSerialControl property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsSerialControl() {
        return isSerialControl;
    }

    /**
     * Sets the value of the isSerialControl property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsSerialControl(Boolean value) {
        this.isSerialControl = value;
    }

    /**
     * Gets the value of the isObsoleteItem property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsObsoleteItem() {
        return isObsoleteItem;
    }

    /**
     * Sets the value of the isObsoleteItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsObsoleteItem(Boolean value) {
        this.isObsoleteItem = value;
    }

    /**
     * Gets the value of the obsoleteAllowancePercent property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getObsoleteAllowancePercent() {
        return obsoleteAllowancePercent;
    }

    /**
     * Sets the value of the obsoleteAllowancePercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setObsoleteAllowancePercent(Double value) {
        this.obsoleteAllowancePercent = value;
    }

    /**
     * Gets the value of the obsoleteAllowanceDuration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObsoleteAllowanceDuration() {
        return obsoleteAllowanceDuration;
    }

    /**
     * Sets the value of the obsoleteAllowanceDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObsoleteAllowanceDuration(String value) {
        this.obsoleteAllowanceDuration = value;
    }

    /**
     * Gets the value of the rtv property.
     * 
     * @return
     *     possible object is
     *     {@link RTVType }
     *     
     */
    public RTVType getRtv() {
        return rtv;
    }

    /**
     * Sets the value of the rtv property.
     * 
     * @param value
     *     allowed object is
     *     {@link RTVType }
     *     
     */
    public void setRtv(RTVType value) {
        this.rtv = value;
    }

    /**
     * Gets the value of the usesEDI810 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUsesEDI810() {
        return usesEDI810;
    }

    /**
     * Sets the value of the usesEDI810 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUsesEDI810(Boolean value) {
        this.usesEDI810 = value;
    }

    /**
     * Gets the value of the usesEDI820 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUsesEDI820() {
        return usesEDI820;
    }

    /**
     * Sets the value of the usesEDI820 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUsesEDI820(Boolean value) {
        this.usesEDI820 = value;
    }

    /**
     * Gets the value of the usesEDI832 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUsesEDI832() {
        return usesEDI832;
    }

    /**
     * Sets the value of the usesEDI832 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUsesEDI832(Boolean value) {
        this.usesEDI832 = value;
    }

    /**
     * Gets the value of the usesEDI846 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUsesEDI846() {
        return usesEDI846;
    }

    /**
     * Sets the value of the usesEDI846 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUsesEDI846(Boolean value) {
        this.usesEDI846 = value;
    }

    /**
     * Gets the value of the usesEDI850 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUsesEDI850() {
        return usesEDI850;
    }

    /**
     * Sets the value of the usesEDI850 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUsesEDI850(Boolean value) {
        this.usesEDI850 = value;
    }

    /**
     * Gets the value of the usesEDI852 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUsesEDI852() {
        return usesEDI852;
    }

    /**
     * Sets the value of the usesEDI852 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUsesEDI852(Boolean value) {
        this.usesEDI852 = value;
    }

    /**
     * Gets the value of the usesEDI855 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUsesEDI855() {
        return usesEDI855;
    }

    /**
     * Sets the value of the usesEDI855 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUsesEDI855(Boolean value) {
        this.usesEDI855 = value;
    }

    /**
     * Gets the value of the usesEDI860 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUsesEDI860() {
        return usesEDI860;
    }

    /**
     * Sets the value of the usesEDI860 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUsesEDI860(Boolean value) {
        this.usesEDI860 = value;
    }

    /**
     * Gets the value of the usesEDI861 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUsesEDI861() {
        return usesEDI861;
    }

    /**
     * Sets the value of the usesEDI861 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUsesEDI861(Boolean value) {
        this.usesEDI861 = value;
    }

    /**
     * Gets the value of the ediDistributionCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEdiDistributionCode() {
        return ediDistributionCode;
    }

    /**
     * Sets the value of the ediDistributionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEdiDistributionCode(String value) {
        this.ediDistributionCode = value;
    }

    /**
     * Gets the value of the shipFromPortId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipFromPortId() {
        return shipFromPortId;
    }

    /**
     * Sets the value of the shipFromPortId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipFromPortId(String value) {
        this.shipFromPortId = value;
    }

    /**
     * Gets the value of the manufacturingSiteId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManufacturingSiteId() {
        return manufacturingSiteId;
    }

    /**
     * Sets the value of the manufacturingSiteId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManufacturingSiteId(String value) {
        this.manufacturingSiteId = value;
    }

    /**
     * Gets the value of the buyingAgentSiteId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuyingAgentSiteId() {
        return buyingAgentSiteId;
    }

    /**
     * Sets the value of the buyingAgentSiteId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuyingAgentSiteId(String value) {
        this.buyingAgentSiteId = value;
    }

    /**
     * Gets the value of the freightForwarderSiteId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreightForwarderSiteId() {
        return freightForwarderSiteId;
    }

    /**
     * Sets the value of the freightForwarderSiteId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreightForwarderSiteId(String value) {
        this.freightForwarderSiteId = value;
    }

}
