//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.03 at 10:48:26 AM CDT 
//


package com.officedepot;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * The document type contains meta-data describing the
 * 				contents of the message.
 * 
 * <p>Java class for TransactionDocumentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransactionDocumentType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="model" type="{http://www.officedepot.com/model/transaction}DocumentModelType" minOccurs="0"/&gt;
 *         &lt;element name="containsSensitiveData" type="{http://www.officedepot.com/model/transaction}HasSensitiveDataType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransactionDocumentType", namespace = "http://www.officedepot.com/model/transaction", propOrder = {
    "model",
    "containsSensitiveData"
})
public class TransactionDocumentType {

    protected DocumentModelType model;
    protected boolean containsSensitiveData;

    /**
     * Gets the value of the model property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentModelType }
     *     
     */
    public DocumentModelType getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentModelType }
     *     
     */
    public void setModel(DocumentModelType value) {
        this.model = value;
    }

    /**
     * Gets the value of the containsSensitiveData property.
     * 
     */
    public boolean isContainsSensitiveData() {
        return containsSensitiveData;
    }

    /**
     * Sets the value of the containsSensitiveData property.
     * 
     */
    public void setContainsSensitiveData(boolean value) {
        this.containsSensitiveData = value;
    }

}
